// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type AccountRemoval struct {
	RunnerID    string
	Harness     string
	Account     string
	RequestedAt int64
}

type AdminToken struct {
	Hash      string
	Name      string
	CreatedAt int64
}

type Event struct {
	RunID      string
	Seq        int64
	Body       string
	ReceivedAt int64
}

type Login struct {
	ID                string
	RunnerID          string
	Harness           string
	Account           string
	Method            string
	State             string
	Url               string
	UserCode          string
	Error             string
	Code              string
	Token             string
	CancelRequestedAt sql.NullInt64
	SentAt            sql.NullInt64
	HubEnded          int64
	CreatedAt         int64
	UpdatedAt         int64
	AddAccount        int64
}

type RegistrationToken struct {
	Hash      string
	CreatedAt int64
	ExpiresAt int64
	ForRunner sql.NullString
	UsedAt    sql.NullInt64
	RunnerID  sql.NullString
}

type Result struct {
	RunID      string
	State      string
	Body       string
	ReceivedAt int64
}

type Run struct {
	ID             string
	SessionID      string
	Harness        string
	Model          string
	Spec           string
	State          string
	RunnerID       sql.NullString
	LeaseExpiresAt sql.NullInt64
	ResumesAt      sql.NullInt64
	Reason         sql.NullString
	CreatedAt      int64
	UpdatedAt      int64
	EventsThrough  int64
}

type RunControl struct {
	ID        int64
	RunID     string
	Kind      string
	Text      string
	CreatedAt int64
}

type Runner struct {
	ID                string
	Name              string
	CredentialHash    string
	Capabilities      string
	Fingerprint       string
	WantsCapabilities int64
	Health            sql.NullString
	RegisteredAt      int64
	LastSyncAt        sql.NullInt64
	DrainRequestedAt  sql.NullInt64
}

type Session struct {
	ID               string
	Harness          string
	RunnerID         sql.NullString
	CreatedAt        int64
	CloseRequestedAt sql.NullInt64
	ClosedAt         sql.NullInt64
	CloseReason      sql.NullString
	OfferedTo        sql.NullString
	CloseOwed        int64
	ForkFrom         sql.NullString
}
