// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const accountRemovals = `-- name: AccountRemovals :many
SELECT runner_id, harness, account, requested_at FROM account_removals WHERE runner_id = ? ORDER BY requested_at, harness, account
`

func (q *Queries) AccountRemovals(ctx context.Context, runnerID string) ([]AccountRemoval, error) {
	rows, err := q.db.QueryContext(ctx, accountRemovals, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountRemoval{}
	for rows.Next() {
		var i AccountRemoval
		if err := rows.Scan(
			&i.RunnerID,
			&i.Harness,
			&i.Account,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addControl = `-- name: AddControl :exec

INSERT INTO run_controls (run_id, kind, text, created_at) VALUES (?, ?, ?, ?)
`

type AddControlParams struct {
	RunID     string
	Kind      string
	Text      string
	CreatedAt int64
}

// Cancel, interrupt and steer (DEV-8).
func (q *Queries) AddControl(ctx context.Context, arg AddControlParams) error {
	_, err := q.db.ExecContext(ctx, addControl,
		arg.RunID,
		arg.Kind,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}

const appendEvent = `-- name: AppendEvent :execrows
INSERT INTO events (run_id, seq, body, received_at) VALUES (?, ?, ?, ?)
ON CONFLICT (run_id, seq) DO NOTHING
`

type AppendEventParams struct {
	RunID      string
	Seq        int64
	Body       string
	ReceivedAt int64
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, appendEvent,
		arg.RunID,
		arg.Seq,
		arg.Body,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindSession = `-- name: BindSession :exec
UPDATE sessions SET runner_id = ? WHERE id = ? AND runner_id IS NULL
`

type BindSessionParams struct {
	RunnerID sql.NullString
	ID       string
}

// The first claim in a session binds it; later ones leave it as it is.
func (q *Queries) BindSession(ctx context.Context, arg BindSessionParams) error {
	_, err := q.db.ExecContext(ctx, bindSession, arg.RunnerID, arg.ID)
	return err
}

const burnRegistrationToken = `-- name: BurnRegistrationToken :execrows
UPDATE registration_tokens SET used_at = ?1, runner_id = ?2
WHERE hash = ?3 AND used_at IS NULL AND expires_at > ?1
`

type BurnRegistrationTokenParams struct {
	Now      sql.NullInt64
	RunnerID sql.NullString
	Hash     string
}

// Burning is one conditional update, so two exchanges racing on one token
// cannot both see it unused.
func (q *Queries) BurnRegistrationToken(ctx context.Context, arg BurnRegistrationTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, burnRegistrationToken, arg.Now, arg.RunnerID, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearDrain = `-- name: ClearDrain :exec
UPDATE runners SET drain_requested_at = NULL WHERE id = ?
`

func (q *Queries) ClearDrain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearDrain, id)
	return err
}

const closeSessionHere = `-- name: CloseSessionHere :execrows
UPDATE sessions SET closed_at = ?1, close_reason = ?2, close_requested_at = NULL
WHERE id = ?3 AND closed_at IS NULL
`

type CloseSessionHereParams struct {
	Now    sql.NullInt64
	Reason sql.NullString
	ID     string
}

// The hub closing a session by its own act (decision 0011), without waiting
// for a runner to report it: one nobody ever claimed, or one whose runner
// deregistered or went silent. A silent runner may still come back, and its
// caller marks the close owed to it (OweSessionClose, decision 0046). A
// repeat changes nothing.
func (q *Queries) CloseSessionHere(ctx context.Context, arg CloseSessionHereParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeSessionHere, arg.Now, arg.Reason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const controlsFor = `-- name: ControlsFor :many
SELECT id, run_id, kind, text, created_at FROM run_controls WHERE run_id = ? ORDER BY id
`

func (q *Queries) ControlsFor(ctx context.Context, runID string) ([]RunControl, error) {
	rows, err := q.db.QueryContext(ctx, controlsFor, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunControl{}
	for rows.Next() {
		var i RunControl
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAdminToken = `-- name: CreateAdminToken :exec

INSERT INTO admin_tokens (hash, name, created_at) VALUES (?, ?, ?)
`

type CreateAdminTokenParams struct {
	Hash      string
	Name      string
	CreatedAt int64
}

// Admin tokens and the service API (DEV-7). Kept in one block so the runner's
// events and result queries can land beside it without a merge fight.
func (q *Queries) CreateAdminToken(ctx context.Context, arg CreateAdminTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAdminToken, arg.Hash, arg.Name, arg.CreatedAt)
	return err
}

const createLogin = `-- name: CreateLogin :exec

INSERT INTO logins (id, runner_id, harness, account, method, token, add_account, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLoginParams struct {
	ID         string
	RunnerID   string
	Harness    string
	Account    string
	Method     string
	Token      string
	AddAccount int64
	CreatedAt  int64
	UpdatedAt  int64
}

// Hub logins (decision 0055).
func (q *Queries) CreateLogin(ctx context.Context, arg CreateLoginParams) error {
	_, err := q.db.ExecContext(ctx, createLogin,
		arg.ID,
		arg.RunnerID,
		arg.Harness,
		arg.Account,
		arg.Method,
		arg.Token,
		arg.AddAccount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRegistrationToken = `-- name: CreateRegistrationToken :exec
INSERT INTO registration_tokens (hash, created_at, expires_at, for_runner) VALUES (?, ?, ?, ?)
`

type CreateRegistrationTokenParams struct {
	Hash      string
	CreatedAt int64
	ExpiresAt int64
	ForRunner sql.NullString
}

func (q *Queries) CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRegistrationToken,
		arg.Hash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ForRunner,
	)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, session_id, harness, model, spec, state, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'queued', ?, ?)
`

type CreateRunParams struct {
	ID        string
	SessionID string
	Harness   string
	Model     string
	Spec      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.SessionID,
		arg.Harness,
		arg.Model,
		arg.Spec,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, harness, created_at) VALUES (?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type CreateSessionParams struct {
	ID        string
	Harness   string
	CreatedAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.Harness, arg.CreatedAt)
	return err
}

const deleteSteersThrough = `-- name: DeleteSteersThrough :exec
DELETE FROM run_controls WHERE run_id = ? AND kind = 'steer' AND id <= ?
`

type DeleteSteersThroughParams struct {
	RunID string
	ID    int64
}

func (q *Queries) DeleteSteersThrough(ctx context.Context, arg DeleteSteersThroughParams) error {
	_, err := q.db.ExecContext(ctx, deleteSteersThrough, arg.RunID, arg.ID)
	return err
}

const endAccountRemoval = `-- name: EndAccountRemoval :exec
DELETE FROM account_removals WHERE runner_id = ? AND harness = ? AND account = ?
`

type EndAccountRemovalParams struct {
	RunnerID string
	Harness  string
	Account  string
}

func (q *Queries) EndAccountRemoval(ctx context.Context, arg EndAccountRemovalParams) error {
	_, err := q.db.ExecContext(ctx, endAccountRemoval, arg.RunnerID, arg.Harness, arg.Account)
	return err
}

const endLogin = `-- name: EndLogin :execrows
UPDATE logins SET state = ?1, error = ?2, url = '', hub_ended = 1, updated_at = ?3
WHERE id = ?4 AND state IN ('requested', 'starting', 'waiting', 'checking')
`

type EndLoginParams struct {
	State string
	Error string
	Now   int64
	ID    string
}

// The hub ending a login by its own act: only ever one no answer has
// carried to its runner, or one its runner can no longer report.
func (q *Queries) EndLogin(ctx context.Context, arg EndLoginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, endLogin,
		arg.State,
		arg.Error,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const endRunnerLogins = `-- name: EndRunnerLogins :execrows
UPDATE logins SET state = 'failed', error = ?1, url = '', hub_ended = 1, updated_at = ?2
WHERE runner_id = ?3 AND state IN ('requested', 'starting', 'waiting', 'checking')
`

type EndRunnerLoginsParams struct {
	Error    string
	Now      int64
	RunnerID string
}

// A runner that deregisters finishes none of its logins.
func (q *Queries) EndRunnerLogins(ctx context.Context, arg EndRunnerLoginsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, endRunnerLogins, arg.Error, arg.Now, arg.RunnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const endUnstartedRun = `-- name: EndUnstartedRun :execrows
UPDATE runs SET state = ?1, reason = ?2, lease_expires_at = NULL, updated_at = ?3
WHERE id = ?4 AND state IN ('queued', 'offered')
`

type EndUnstartedRunParams struct {
	State  string
	Reason sql.NullString
	Now    int64
	ID     string
}

// A run no runner has started ends on the hub alone: cancelled when someone
// asked, failed when what it needed has gone. An offered run keeps its
// runner: that runner lists it once more, hears cancel, and withdraws it.
func (q *Queries) EndUnstartedRun(ctx context.Context, arg EndUnstartedRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, endUnstartedRun,
		arg.State,
		arg.Reason,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const eventSeqsFrom = `-- name: EventSeqsFrom :many

SELECT seq FROM events WHERE run_id = ?1 AND seq > ?2 ORDER BY seq LIMIT ?3
`

type EventSeqsFromParams struct {
	RunID string
	After int64
	Max   int64
}

// Events and results (DEV-6): the protocol's two reporting calls.
func (q *Queries) EventSeqsFrom(ctx context.Context, arg EventSeqsFromParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, eventSeqsFrom, arg.RunID, arg.After, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var seq int64
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsAfter = `-- name: EventsAfter :many
SELECT seq, body FROM events WHERE run_id = ? AND seq > ? ORDER BY seq LIMIT ?
`

type EventsAfterParams struct {
	RunID string
	Seq   int64
	Limit int64
}

type EventsAfterRow struct {
	Seq  int64
	Body string
}

func (q *Queries) EventsAfter(ctx context.Context, arg EventsAfterParams) ([]EventsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, eventsAfter, arg.RunID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsAfterRow{}
	for rows.Next() {
		var i EventsAfterRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsContiguous = `-- name: EventsContiguous :many
SELECT e.seq, e.body FROM events e JOIN runs r ON r.id = e.run_id
WHERE e.run_id = ?1 AND e.seq > ?2 AND e.seq <= r.events_through
ORDER BY e.seq LIMIT ?3
`

type EventsContiguousParams struct {
	RunID string
	After int64
	Max   int64
}

type EventsContiguousRow struct {
	Seq  int64
	Body string
}

// A watcher reads only as far as the stream is contiguous: an event stored
// past a gap waits until the gap is filled, or a cursor would move past the
// missing seq and never see it.
func (q *Queries) EventsContiguous(ctx context.Context, arg EventsContiguousParams) ([]EventsContiguousRow, error) {
	rows, err := q.db.QueryContext(ctx, eventsContiguous, arg.RunID, arg.After, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsContiguousRow{}
	for rows.Next() {
		var i EventsContiguousRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireStaleLogins = `-- name: ExpireStaleLogins :execrows
UPDATE logins SET state = 'failed', error = ?1, url = '', hub_ended = 1, updated_at = ?2
WHERE (state IN ('starting', 'waiting', 'checking') OR state = 'requested' AND sent_at IS NOT NULL)
  AND created_at <= ?3
`

type ExpireStaleLoginsParams struct {
	Error  string
	Now    int64
	Cutoff int64
}

// Logins sent to a runner and not finished by the cutoff, which is well past
// every deadline a runner holds one to: it stopped reporting them.
func (q *Queries) ExpireStaleLogins(ctx context.Context, arg ExpireStaleLoginsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireStaleLogins, arg.Error, arg.Now, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireUndeliveredLogins = `-- name: ExpireUndeliveredLogins :execrows
UPDATE logins SET state = 'expired', error = ?1, hub_ended = 1, updated_at = ?2
WHERE state = 'requested' AND sent_at IS NULL AND created_at <= ?3
`

type ExpireUndeliveredLoginsParams struct {
	Error  string
	Now    int64
	Cutoff int64
}

// Logins no answer carried to their runner by the cutoff: it is not syncing,
// and a token must not wait in this database for it to come back. One an
// answer did carry is the runner's, and falls to ExpireStaleLogins.
func (q *Queries) ExpireUndeliveredLogins(ctx context.Context, arg ExpireUndeliveredLoginsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireUndeliveredLogins, arg.Error, arg.Now, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishRun = `-- name: FinishRun :exec
UPDATE runs SET state = ?, reason = ?, lease_expires_at = NULL, resumes_at = NULL, updated_at = ?
WHERE id = ?
`

type FinishRunParams struct {
	State     string
	Reason    sql.NullString
	UpdatedAt int64
	ID        string
}

// The result settles the run: its state, the reason a failure gave, and no
// lease any more, so a finished run cannot lapse into lost.
func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.State,
		arg.Reason,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const firstControl = `-- name: FirstControl :one
SELECT id, run_id, kind, text, created_at FROM run_controls WHERE run_id = ? AND kind = ? ORDER BY id LIMIT 1
`

type FirstControlParams struct {
	RunID string
	Kind  string
}

func (q *Queries) FirstControl(ctx context.Context, arg FirstControlParams) (RunControl, error) {
	row := q.db.QueryRowContext(ctx, firstControl, arg.RunID, arg.Kind)
	var i RunControl
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountRemoval = `-- name: GetAccountRemoval :one
SELECT runner_id, harness, account, requested_at FROM account_removals WHERE runner_id = ? AND harness = ? AND account = ?
`

type GetAccountRemovalParams struct {
	RunnerID string
	Harness  string
	Account  string
}

func (q *Queries) GetAccountRemoval(ctx context.Context, arg GetAccountRemovalParams) (AccountRemoval, error) {
	row := q.db.QueryRowContext(ctx, getAccountRemoval, arg.RunnerID, arg.Harness, arg.Account)
	var i AccountRemoval
	err := row.Scan(
		&i.RunnerID,
		&i.Harness,
		&i.Account,
		&i.RequestedAt,
	)
	return i, err
}

const getAdminToken = `-- name: GetAdminToken :one
SELECT hash, name, created_at FROM admin_tokens WHERE hash = ?
`

func (q *Queries) GetAdminToken(ctx context.Context, hash string) (AdminToken, error) {
	row := q.db.QueryRowContext(ctx, getAdminToken, hash)
	var i AdminToken
	err := row.Scan(&i.Hash, &i.Name, &i.CreatedAt)
	return i, err
}

const getLogin = `-- name: GetLogin :one
SELECT id, runner_id, harness, account, method, state, url, user_code, error, code, token, cancel_requested_at, sent_at, hub_ended, created_at, updated_at, add_account FROM logins WHERE id = ?
`

func (q *Queries) GetLogin(ctx context.Context, id string) (Login, error) {
	row := q.db.QueryRowContext(ctx, getLogin, id)
	var i Login
	err := row.Scan(
		&i.ID,
		&i.RunnerID,
		&i.Harness,
		&i.Account,
		&i.Method,
		&i.State,
		&i.Url,
		&i.UserCode,
		&i.Error,
		&i.Code,
		&i.Token,
		&i.CancelRequestedAt,
		&i.SentAt,
		&i.HubEnded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AddAccount,
	)
	return i, err
}

const getRegistrationToken = `-- name: GetRegistrationToken :one
SELECT hash, created_at, expires_at, for_runner, used_at, runner_id FROM registration_tokens WHERE hash = ?
`

func (q *Queries) GetRegistrationToken(ctx context.Context, hash string) (RegistrationToken, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationToken, hash)
	var i RegistrationToken
	err := row.Scan(
		&i.Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ForRunner,
		&i.UsedAt,
		&i.RunnerID,
	)
	return i, err
}

const getResult = `-- name: GetResult :one
SELECT run_id, state, body, received_at FROM results WHERE run_id = ?
`

func (q *Queries) GetResult(ctx context.Context, runID string) (Result, error) {
	row := q.db.QueryRowContext(ctx, getResult, runID)
	var i Result
	err := row.Scan(
		&i.RunID,
		&i.State,
		&i.Body,
		&i.ReceivedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, session_id, harness, model, spec, state, runner_id, lease_expires_at, resumes_at, reason, created_at, updated_at, events_through FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Harness,
		&i.Model,
		&i.Spec,
		&i.State,
		&i.RunnerID,
		&i.LeaseExpiresAt,
		&i.ResumesAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventsThrough,
	)
	return i, err
}

const getRunner = `-- name: GetRunner :one
SELECT id, name, credential_hash, capabilities, fingerprint, wants_capabilities, health, registered_at, last_sync_at, drain_requested_at FROM runners WHERE id = ?
`

func (q *Queries) GetRunner(ctx context.Context, id string) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunner, id)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialHash,
		&i.Capabilities,
		&i.Fingerprint,
		&i.WantsCapabilities,
		&i.Health,
		&i.RegisteredAt,
		&i.LastSyncAt,
		&i.DrainRequestedAt,
	)
	return i, err
}

const getRunnerByCredential = `-- name: GetRunnerByCredential :one
SELECT id, name, credential_hash, capabilities, fingerprint, wants_capabilities, health, registered_at, last_sync_at, drain_requested_at FROM runners WHERE credential_hash = ?
`

func (q *Queries) GetRunnerByCredential(ctx context.Context, credentialHash string) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunnerByCredential, credentialHash)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialHash,
		&i.Capabilities,
		&i.Fingerprint,
		&i.WantsCapabilities,
		&i.Health,
		&i.RegisteredAt,
		&i.LastSyncAt,
		&i.DrainRequestedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, harness, runner_id, created_at, close_requested_at, closed_at, close_reason, offered_to, close_owed FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Harness,
		&i.RunnerID,
		&i.CreatedAt,
		&i.CloseRequestedAt,
		&i.ClosedAt,
		&i.CloseReason,
		&i.OfferedTo,
		&i.CloseOwed,
	)
	return i, err
}

const listAdminTokens = `-- name: ListAdminTokens :many
SELECT name, created_at FROM admin_tokens ORDER BY name
`

type ListAdminTokensRow struct {
	Name      string
	CreatedAt int64
}

func (q *Queries) ListAdminTokens(ctx context.Context) ([]ListAdminTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminTokensRow{}
	for rows.Next() {
		var i ListAdminTokensRow
		if err := rows.Scan(&i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunners = `-- name: ListRunners :many
SELECT id, name, credential_hash, capabilities, fingerprint, wants_capabilities, health, registered_at, last_sync_at, drain_requested_at FROM runners ORDER BY last_sync_at IS NULL, last_sync_at DESC, id
`

// Every runner this hub knows. The ones still talking to it come first, so an
// operator reading the list sees the live fleet before the retired machines;
// a runner that registered and never synced sorts last, by id.
func (q *Queries) ListRunners(ctx context.Context) ([]Runner, error) {
	rows, err := q.db.QueryContext(ctx, listRunners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Runner{}
	for rows.Next() {
		var i Runner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CredentialHash,
			&i.Capabilities,
			&i.Fingerprint,
			&i.WantsCapabilities,
			&i.Health,
			&i.RegisteredAt,
			&i.LastSyncAt,
			&i.DrainRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loseLapsedRuns = `-- name: LoseLapsedRuns :execrows
UPDATE runs SET state = 'lost', reason = 'the runner stopped syncing and its lease lapsed', updated_at = ?1
WHERE state IN ('claimed', 'preparing', 'running', 'waiting') AND lease_expires_at <= ?1
`

func (q *Queries) LoseLapsedRuns(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, loseLapsedRuns, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const loseRunnerRuns = `-- name: LoseRunnerRuns :execrows
UPDATE runs SET state = 'lost', reason = ?1, lease_expires_at = NULL, resumes_at = NULL,
  updated_at = ?2
WHERE runner_id = ?3 AND state IN ('claimed', 'preparing', 'running', 'waiting')
`

type LoseRunnerRunsParams struct {
	Reason   sql.NullString
	Now      int64
	RunnerID sql.NullString
}

// Runs a departed runner held are lost: it is not coming back to report
// them, and lost is what a hub tells a submitter then (decision 0023).
func (q *Queries) LoseRunnerRuns(ctx context.Context, arg LoseRunnerRunsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, loseRunnerRuns, arg.Reason, arg.Now, arg.RunnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markLoginSent = `-- name: MarkLoginSent :exec
UPDATE logins SET sent_at = COALESCE(sent_at, ?1) WHERE id = ?2
`

type MarkLoginSentParams struct {
	Now sql.NullInt64
	ID  string
}

// A sync's answer carries the login's start: from now the runner may have it.
func (q *Queries) MarkLoginSent(ctx context.Context, arg MarkLoginSentParams) error {
	_, err := q.db.ExecContext(ctx, markLoginSent, arg.Now, arg.ID)
	return err
}

const noteSessionOffer = `-- name: NoteSessionOffer :exec
UPDATE sessions SET offered_to = ?1 WHERE id = ?2 AND runner_id IS NULL
`

type NoteSessionOfferParams struct {
	RunnerID sql.NullString
	ID       string
}

// Until a claim binds it, a session remembers the runner its run was last
// offered to: the one runner whose report of closing it is believed.
func (q *Queries) NoteSessionOffer(ctx context.Context, arg NoteSessionOfferParams) error {
	_, err := q.db.ExecContext(ctx, noteSessionOffer, arg.RunnerID, arg.ID)
	return err
}

const offerCandidates = `-- name: OfferCandidates :many
SELECT r.id, r.session_id, r.harness, r.model, r.spec, r.state, r.runner_id, r.lease_expires_at, r.resumes_at, r.reason, r.created_at, r.updated_at, r.events_through FROM runs r JOIN sessions s ON s.id = r.session_id
WHERE r.state = 'queued'
  AND s.close_requested_at IS NULL AND s.closed_at IS NULL
  AND r.harness IN (SELECT value FROM json_each(?1))
  AND (r.created_at > ?2 OR (r.created_at = ?2 AND r.id > ?3))
  AND (s.runner_id IS NULL OR s.runner_id = ?4)
  AND NOT EXISTS (
      SELECT 1 FROM runs o
      WHERE o.session_id = r.session_id
        AND o.state IN ('offered', 'claimed', 'preparing', 'running', 'waiting'))
  AND NOT EXISTS (
      SELECT 1 FROM runs e
      WHERE e.session_id = r.session_id AND e.state = 'queued'
        AND (e.created_at < r.created_at OR (e.created_at = r.created_at AND e.id < r.id)))
ORDER BY r.created_at, r.id
LIMIT ?5
`

type OfferCandidatesParams struct {
	HarnessesJson  interface{}
	AfterCreatedAt int64
	AfterID        string
	RunnerID       sql.NullString
	Max            int64
}

// Queued runs this runner may be offered, oldest first, a page at a time
// after the (created_at, id) cursor: only harnesses it can take now, only the
// oldest queued run of each session, only in a session that is unbound or
// bound to it, and never while another run of that session is out, since a
// session has at most one live run. Nor in a session whose close is asked
// for: the runner acts on close_session before the offers beside it and would
// refuse the run, which instead ends with the close once reported (DEV-120).
// Filtering here rather than in Go is what keeps runs it must skip from
// filling the page ahead of runs it could take.
func (q *Queries) OfferCandidates(ctx context.Context, arg OfferCandidatesParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, offerCandidates,
		arg.HarnessesJson,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RunnerID,
		arg.Max,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.Spec,
			&i.State,
			&i.RunnerID,
			&i.LeaseExpiresAt,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventsThrough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offerRun = `-- name: OfferRun :exec
UPDATE runs SET state = 'offered', runner_id = ?, lease_expires_at = ?, updated_at = ?
WHERE id = ? AND state = 'queued'
`

type OfferRunParams struct {
	RunnerID       sql.NullString
	LeaseExpiresAt sql.NullInt64
	UpdatedAt      int64
	ID             string
}

func (q *Queries) OfferRun(ctx context.Context, arg OfferRunParams) error {
	_, err := q.db.ExecContext(ctx, offerRun,
		arg.RunnerID,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const openLogins = `-- name: OpenLogins :many
SELECT id, runner_id, harness, account, method, state, url, user_code, error, code, token, cancel_requested_at, sent_at, hub_ended, created_at, updated_at, add_account FROM logins WHERE runner_id = ? AND state IN ('requested', 'starting', 'waiting', 'checking')
ORDER BY created_at, id
`

// Every login of this runner not yet over, oldest first.
func (q *Queries) OpenLogins(ctx context.Context, runnerID string) ([]Login, error) {
	rows, err := q.db.QueryContext(ctx, openLogins, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Login{}
	for rows.Next() {
		var i Login
		if err := rows.Scan(
			&i.ID,
			&i.RunnerID,
			&i.Harness,
			&i.Account,
			&i.Method,
			&i.State,
			&i.Url,
			&i.UserCode,
			&i.Error,
			&i.Code,
			&i.Token,
			&i.CancelRequestedAt,
			&i.SentAt,
			&i.HubEnded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openLoginsFor = `-- name: OpenLoginsFor :many
SELECT id, runner_id, harness, account, method, state, url, user_code, error, code, token, cancel_requested_at, sent_at, hub_ended, created_at, updated_at, add_account FROM logins WHERE runner_id = ?1 AND harness = ?2 AND account = ?3
  AND state IN ('requested', 'starting', 'waiting', 'checking')
ORDER BY created_at, id
`

type OpenLoginsForParams struct {
	RunnerID string
	Harness  string
	Account  string
}

// The open logins of one account on one runner: what a new login for it
// replaces.
func (q *Queries) OpenLoginsFor(ctx context.Context, arg OpenLoginsForParams) ([]Login, error) {
	rows, err := q.db.QueryContext(ctx, openLoginsFor, arg.RunnerID, arg.Harness, arg.Account)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Login{}
	for rows.Next() {
		var i Login
		if err := rows.Scan(
			&i.ID,
			&i.RunnerID,
			&i.Harness,
			&i.Account,
			&i.Method,
			&i.State,
			&i.Url,
			&i.UserCode,
			&i.Error,
			&i.Code,
			&i.Token,
			&i.CancelRequestedAt,
			&i.SentAt,
			&i.HubEnded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oweSessionClose = `-- name: OweSessionClose :exec
UPDATE sessions SET close_owed = 1 WHERE id = ?1 AND runner_id IS NOT NULL
`

// The hub closed it by its own act and the runner has not heard yet: the
// close_session goes out until the runner reports the session closed.
func (q *Queries) OweSessionClose(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, oweSessionClose, id)
	return err
}

const putResult = `-- name: PutResult :execrows
INSERT INTO results (run_id, state, body, received_at) VALUES (?, ?, ?, ?)
ON CONFLICT (run_id) DO NOTHING
`

type PutResultParams struct {
	RunID      string
	State      string
	Body       string
	ReceivedAt int64
}

func (q *Queries) PutResult(ctx context.Context, arg PutResultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, putResult,
		arg.RunID,
		arg.State,
		arg.Body,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordLoginReport = `-- name: RecordLoginReport :execrows
UPDATE logins SET state = ?1, url = ?2, user_code = ?3, error = ?4,
  hub_ended = 0,
  updated_at = CASE WHEN state = ?1 THEN updated_at ELSE ?5 END
WHERE id = ?6 AND runner_id = ?7
  AND (state IN ('requested', 'starting', 'waiting', 'checking')
    OR hub_ended = 1 AND CAST(?8 AS INTEGER) = 1)
`

type RecordLoginReportParams struct {
	State    string
	Url      string
	UserCode string
	Error    string
	Now      int64
	ID       string
	RunnerID string
	Terminal int64
}

// A runner's report of a login this hub started on it. An end the runner
// reported stands; an end the hub made by its own act gives way to the
// runner's own report of an end, which knows what happened on the machine.
// A report about another runner's login changes nothing. updated_at moves
// only with the state, so it says when the login last did.
func (q *Queries) RecordLoginReport(ctx context.Context, arg RecordLoginReportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordLoginReport,
		arg.State,
		arg.Url,
		arg.UserCode,
		arg.Error,
		arg.Now,
		arg.ID,
		arg.RunnerID,
		arg.Terminal,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordSessionClosed = `-- name: RecordSessionClosed :execrows
UPDATE sessions SET closed_at = ?1, close_reason = ?2, close_requested_at = NULL,
  runner_id = ?3
WHERE id = ?4 AND closed_at IS NULL
  AND (runner_id = ?3 OR (runner_id IS NULL AND offered_to = ?3))
`

type RecordSessionClosedParams struct {
	ClosedAt sql.NullInt64
	Reason   sql.NullString
	RunnerID sql.NullString
	ID       string
}

// A runner's report closes a session bound to it, or an unbound one whose
// run was last offered to it: its claim may have been withdrawn before any
// sync listed it, and the close its owner asked for meanwhile is still owed
// (DEV-103). Such a session is bound to the reporter as it closes, since
// whatever it left is on that runner's disk. A repeat changes nothing, and a
// report from any other runner is not applied.
func (q *Queries) RecordSessionClosed(ctx context.Context, arg RecordSessionClosedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordSessionClosed,
		arg.ClosedAt,
		arg.Reason,
		arg.RunnerID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordSync = `-- name: RecordSync :exec
UPDATE runners SET last_sync_at = ?, health = ?, wants_capabilities = ? WHERE id = ?
`

type RecordSyncParams struct {
	LastSyncAt        sql.NullInt64
	Health            sql.NullString
	WantsCapabilities int64
	ID                string
}

func (q *Queries) RecordSync(ctx context.Context, arg RecordSyncParams) error {
	_, err := q.db.ExecContext(ctx, recordSync,
		arg.LastSyncAt,
		arg.Health,
		arg.WantsCapabilities,
		arg.ID,
	)
	return err
}

const renewRun = `-- name: RenewRun :exec
UPDATE runs SET state = ?, lease_expires_at = ?, resumes_at = ?, reason = ?, updated_at = ?
WHERE id = ? AND runner_id = ?
`

type RenewRunParams struct {
	State          string
	LeaseExpiresAt sql.NullInt64
	ResumesAt      sql.NullInt64
	Reason         sql.NullString
	UpdatedAt      int64
	ID             string
	RunnerID       sql.NullString
}

// Listing a run claims it (when offered) and renews its lease (always).
func (q *Queries) RenewRun(ctx context.Context, arg RenewRunParams) error {
	_, err := q.db.ExecContext(ctx, renewRun,
		arg.State,
		arg.LeaseExpiresAt,
		arg.ResumesAt,
		arg.Reason,
		arg.UpdatedAt,
		arg.ID,
		arg.RunnerID,
	)
	return err
}

const requestAccountRemoval = `-- name: RequestAccountRemoval :exec

INSERT INTO account_removals (runner_id, harness, account, requested_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (runner_id, harness, account) DO NOTHING
`

type RequestAccountRemovalParams struct {
	RunnerID    string
	Harness     string
	Account     string
	RequestedAt int64
}

// Removing a runner's accounts (decision 0057).
// A repeat keeps the first request's time: it is the same removal.
func (q *Queries) RequestAccountRemoval(ctx context.Context, arg RequestAccountRemovalParams) error {
	_, err := q.db.ExecContext(ctx, requestAccountRemoval,
		arg.RunnerID,
		arg.Harness,
		arg.Account,
		arg.RequestedAt,
	)
	return err
}

const requestDrain = `-- name: RequestDrain :exec
UPDATE runners SET drain_requested_at = COALESCE(drain_requested_at, ?1) WHERE id = ?2
`

type RequestDrainParams struct {
	Now sql.NullInt64
	ID  string
}

func (q *Queries) RequestDrain(ctx context.Context, arg RequestDrainParams) error {
	_, err := q.db.ExecContext(ctx, requestDrain, arg.Now, arg.ID)
	return err
}

const requestLoginCancel = `-- name: RequestLoginCancel :exec
UPDATE logins SET cancel_requested_at = COALESCE(cancel_requested_at, ?1)
WHERE id = ?2 AND state IN ('requested', 'starting', 'waiting', 'checking')
`

type RequestLoginCancelParams struct {
	Now sql.NullInt64
	ID  string
}

func (q *Queries) RequestLoginCancel(ctx context.Context, arg RequestLoginCancelParams) error {
	_, err := q.db.ExecContext(ctx, requestLoginCancel, arg.Now, arg.ID)
	return err
}

const requestSessionClose = `-- name: RequestSessionClose :exec
UPDATE sessions SET close_requested_at = COALESCE(close_requested_at, ?1)
WHERE id = ?2 AND closed_at IS NULL
`

type RequestSessionCloseParams struct {
	Now sql.NullInt64
	ID  string
}

func (q *Queries) RequestSessionClose(ctx context.Context, arg RequestSessionCloseParams) error {
	_, err := q.db.ExecContext(ctx, requestSessionClose, arg.Now, arg.ID)
	return err
}

const requeueRun = `-- name: RequeueRun :exec
UPDATE runs SET state = 'queued', runner_id = NULL, lease_expires_at = NULL, updated_at = ?
WHERE id = ? AND state = 'offered'
`

type RequeueRunParams struct {
	UpdatedAt int64
	ID        string
}

// An offer the runner did not list back was never received: the run goes back
// in the queue, for this runner or another.
func (q *Queries) RequeueRun(ctx context.Context, arg RequeueRunParams) error {
	_, err := q.db.ExecContext(ctx, requeueRun, arg.UpdatedAt, arg.ID)
	return err
}

const requeueRunnerOffers = `-- name: RequeueRunnerOffers :execrows
UPDATE runs SET state = 'queued', runner_id = NULL, lease_expires_at = NULL, updated_at = ?1
WHERE runner_id = ?2 AND state = 'offered'
`

type RequeueRunnerOffersParams struct {
	Now      int64
	RunnerID sql.NullString
}

// An offer it never claimed was never held, so it goes back in the queue
// rather than being lost.
func (q *Queries) RequeueRunnerOffers(ctx context.Context, arg RequeueRunnerOffersParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueRunnerOffers, arg.Now, arg.RunnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueWithdrawnOffers = `-- name: RequeueWithdrawnOffers :execrows
UPDATE runs SET state = 'queued', runner_id = NULL, lease_expires_at = NULL, updated_at = ?1
WHERE state = 'offered' AND lease_expires_at <= ?1
`

func (q *Queries) RequeueWithdrawnOffers(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueWithdrawnOffers, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retireRunnerCredential = `-- name: RetireRunnerCredential :exec
UPDATE runners SET credential_hash = ?1, drain_requested_at = NULL
WHERE id = ?2
`

type RetireRunnerCredentialParams struct {
	CredentialHash string
	ID             string
}

// Deregistration. A runner that deregisters keeps its row: sessions and runs
// reference it, and re-registering under a token issued for that id is how it
// comes back. What goes is its credential, replaced by the hash of a secret
// nobody was given, so nothing can authenticate as it again.
func (q *Queries) RetireRunnerCredential(ctx context.Context, arg RetireRunnerCredentialParams) error {
	_, err := q.db.ExecContext(ctx, retireRunnerCredential, arg.CredentialHash, arg.ID)
	return err
}

const revokeAdminToken = `-- name: RevokeAdminToken :execrows
DELETE FROM admin_tokens WHERE name = ?
`

func (q *Queries) RevokeAdminToken(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAdminToken, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const runsOfferedTo = `-- name: RunsOfferedTo :many
SELECT id, session_id, harness, model, spec, state, runner_id, lease_expires_at, resumes_at, reason, created_at, updated_at, events_through FROM runs WHERE runner_id = ? AND state = 'offered'
`

func (q *Queries) RunsOfferedTo(ctx context.Context, runnerID sql.NullString) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, runsOfferedTo, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.Spec,
			&i.State,
			&i.RunnerID,
			&i.LeaseExpiresAt,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventsThrough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionCreatorSpec = `-- name: SessionCreatorSpec :one
SELECT spec FROM runs WHERE session_id = ? AND json_extract(spec, '$.session.new') = 1
ORDER BY created_at, id LIMIT 1
`

// The spec of the run whose submission created the session: the one its
// submitter sent as new. Found by that flag rather than by order, since a
// continuation submitted in the same millisecond can sort ahead of it.
func (q *Queries) SessionCreatorSpec(ctx context.Context, sessionID string) (string, error) {
	row := q.db.QueryRowContext(ctx, sessionCreatorSpec, sessionID)
	var spec string
	err := row.Scan(&spec)
	return spec, err
}

const sessionsToClose = `-- name: SessionsToClose :many
SELECT id FROM sessions
WHERE runner_id = ?1 AND (close_requested_at IS NOT NULL AND closed_at IS NULL OR close_owed = 1)
ORDER BY id
`

// The sessions close_session goes to this runner for: a close asked for and
// not yet reported, and one the hub closed while the runner was silent, whose
// workdir the runner still holds (decision 0046).
func (q *Queries) SessionsToClose(ctx context.Context, runnerID sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, sessionsToClose, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionsToSettle = `-- name: SessionsToSettle :many
SELECT id FROM sessions WHERE runner_id = ?1 AND closed_at IS NULL ORDER BY id
`

// A departed runner's sessions that still need the hub: the open ones. A
// closed one holds no waiting run, because every close ends those.
func (q *Queries) SessionsToSettle(ctx context.Context, runnerID sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, sessionsToSettle, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCapabilities = `-- name: SetCapabilities :exec
UPDATE runners SET capabilities = ?, fingerprint = ?, wants_capabilities = 0 WHERE id = ?
`

type SetCapabilitiesParams struct {
	Capabilities string
	Fingerprint  string
	ID           string
}

func (q *Queries) SetCapabilities(ctx context.Context, arg SetCapabilitiesParams) error {
	_, err := q.db.ExecContext(ctx, setCapabilities, arg.Capabilities, arg.Fingerprint, arg.ID)
	return err
}

const setEventsThrough = `-- name: SetEventsThrough :exec
UPDATE runs SET events_through = ? WHERE id = ?
`

type SetEventsThroughParams struct {
	EventsThrough int64
	ID            string
}

func (q *Queries) SetEventsThrough(ctx context.Context, arg SetEventsThroughParams) error {
	_, err := q.db.ExecContext(ctx, setEventsThrough, arg.EventsThrough, arg.ID)
	return err
}

const setLoginCode = `-- name: SetLoginCode :exec
UPDATE logins SET code = ?1 WHERE id = ?2 AND state = 'waiting'
`

type SetLoginCodeParams struct {
	Code string
	ID   string
}

func (q *Queries) SetLoginCode(ctx context.Context, arg SetLoginCodeParams) error {
	_, err := q.db.ExecContext(ctx, setLoginCode, arg.Code, arg.ID)
	return err
}

const settleOwedClose = `-- name: SettleOwedClose :exec
UPDATE sessions SET close_owed = 0 WHERE id = ?1 AND runner_id = ?2 AND close_owed = 1
`

type SettleOwedCloseParams struct {
	ID       string
	RunnerID sql.NullString
}

// The runner holding the session reported it closed, which answers every
// close_session it was owed. A report from any other runner answers nothing.
func (q *Queries) SettleOwedClose(ctx context.Context, arg SettleOwedCloseParams) error {
	_, err := q.db.ExecContext(ctx, settleOwedClose, arg.ID, arg.RunnerID)
	return err
}

const silentRunners = `-- name: SilentRunners :many
SELECT DISTINCT r.id FROM runners r JOIN sessions s ON s.runner_id = r.id
WHERE s.closed_at IS NULL AND r.last_sync_at IS NOT NULL AND r.last_sync_at <= ?1
ORDER BY r.id
`

// Runners silent since before the cutoff that still have an open session
// bound to them (decision 0046). Silence counts from the last sync the hub
// answered; a runner that never synced has no session bound to it, because
// only a sync's listing binds one.
func (q *Queries) SilentRunners(ctx context.Context, cutoff sql.NullInt64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, silentRunners, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const soonCandidates = `-- name: SoonCandidates :many
SELECT r.id, r.session_id, r.harness, r.model, r.spec, r.state, r.runner_id, r.lease_expires_at, r.resumes_at, r.reason, r.created_at, r.updated_at, r.events_through FROM runs r JOIN sessions s ON s.id = r.session_id
WHERE r.state = 'queued'
  AND s.close_requested_at IS NULL AND s.closed_at IS NULL
  AND r.harness IN (SELECT value FROM json_each(?1))
  AND (r.created_at > ?2 OR (r.created_at = ?2 AND r.id > ?3))
  AND (s.runner_id = ?4 OR (s.runner_id IS NULL AND NOT EXISTS (
      SELECT 1 FROM runs o
      WHERE o.session_id = r.session_id
        AND o.state IN ('offered', 'claimed', 'preparing', 'running', 'waiting'))))
  AND NOT EXISTS (
      SELECT 1 FROM runs e
      WHERE e.session_id = r.session_id AND e.state = 'queued'
        AND (e.created_at < r.created_at OR (e.created_at = r.created_at AND e.id < r.id)))
ORDER BY r.created_at, r.id
LIMIT ?5
`

type SoonCandidatesParams struct {
	HarnessesJson  interface{}
	AfterCreatedAt int64
	AfterID        string
	RunnerID       sql.NullString
	Max            int64
}

// Queued runs this runner would be offered once a run it holds ends: the
// rules of OfferCandidates, except that a session bound to it may have a run
// out, since that run is this runner's and ending it is what lets the next
// one go. An unbound session with a run out is left out: that run may be on
// its way to another runner, whose claim would bind the session there.
func (q *Queries) SoonCandidates(ctx context.Context, arg SoonCandidatesParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, soonCandidates,
		arg.HarnessesJson,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RunnerID,
		arg.Max,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.Spec,
			&i.State,
			&i.RunnerID,
			&i.LeaseExpiresAt,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventsThrough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unstartedRunsInSession = `-- name: UnstartedRunsInSession :many
SELECT id FROM runs WHERE session_id = ? AND state IN ('queued', 'offered') ORDER BY created_at, id
`

func (q *Queries) UnstartedRunsInSession(ctx context.Context, sessionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, unstartedRunsInSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRunner = `-- name: UpsertRunner :exec
INSERT INTO runners (id, name, credential_hash, capabilities, fingerprint, registered_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    credential_hash = excluded.credential_hash,
    capabilities = excluded.capabilities,
    fingerprint = excluded.fingerprint,
    wants_capabilities = 0,
    registered_at = excluded.registered_at
`

type UpsertRunnerParams struct {
	ID             string
	Name           string
	CredentialHash string
	Capabilities   string
	Fingerprint    string
	RegisteredAt   int64
}

// Registering an id that exists replaces its credential: the old one dies,
// which is how a runner that lost its credential file is recovered. The
// caller checks the token was issued for that id first.
func (q *Queries) UpsertRunner(ctx context.Context, arg UpsertRunnerParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunner,
		arg.ID,
		arg.Name,
		arg.CredentialHash,
		arg.Capabilities,
		arg.Fingerprint,
		arg.RegisteredAt,
	)
	return err
}
