// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const appendEvent = `-- name: AppendEvent :execrows
INSERT INTO events (run_id, seq, body, received_at) VALUES (?, ?, ?, ?)
ON CONFLICT (run_id, seq) DO NOTHING
`

type AppendEventParams struct {
	RunID      string
	Seq        int64
	Body       string
	ReceivedAt int64
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, appendEvent,
		arg.RunID,
		arg.Seq,
		arg.Body,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindSession = `-- name: BindSession :exec
UPDATE sessions SET runner_id = ? WHERE id = ? AND runner_id IS NULL
`

type BindSessionParams struct {
	RunnerID sql.NullString
	ID       string
}

// The first claim in a session binds it; later ones leave it as it is.
func (q *Queries) BindSession(ctx context.Context, arg BindSessionParams) error {
	_, err := q.db.ExecContext(ctx, bindSession, arg.RunnerID, arg.ID)
	return err
}

const burnRegistrationToken = `-- name: BurnRegistrationToken :execrows
UPDATE registration_tokens SET used_at = ?1, runner_id = ?2
WHERE hash = ?3 AND used_at IS NULL AND expires_at > ?1
`

type BurnRegistrationTokenParams struct {
	Now      sql.NullInt64
	RunnerID sql.NullString
	Hash     string
}

// Burning is one conditional update, so two exchanges racing on one token
// cannot both see it unused.
func (q *Queries) BurnRegistrationToken(ctx context.Context, arg BurnRegistrationTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, burnRegistrationToken, arg.Now, arg.RunnerID, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAdminToken = `-- name: CreateAdminToken :exec

INSERT INTO admin_tokens (hash, name, created_at) VALUES (?, ?, ?)
`

type CreateAdminTokenParams struct {
	Hash      string
	Name      string
	CreatedAt int64
}

// Admin tokens and the service API (DEV-7). Kept in one block so the runner's
// events and result queries can land beside it without a merge fight.
func (q *Queries) CreateAdminToken(ctx context.Context, arg CreateAdminTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAdminToken, arg.Hash, arg.Name, arg.CreatedAt)
	return err
}

const createRegistrationToken = `-- name: CreateRegistrationToken :exec
INSERT INTO registration_tokens (hash, created_at, expires_at, for_runner) VALUES (?, ?, ?, ?)
`

type CreateRegistrationTokenParams struct {
	Hash      string
	CreatedAt int64
	ExpiresAt int64
	ForRunner sql.NullString
}

func (q *Queries) CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRegistrationToken,
		arg.Hash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ForRunner,
	)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, session_id, harness, model, spec, state, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'queued', ?, ?)
`

type CreateRunParams struct {
	ID        string
	SessionID string
	Harness   string
	Model     string
	Spec      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.SessionID,
		arg.Harness,
		arg.Model,
		arg.Spec,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, harness, created_at) VALUES (?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type CreateSessionParams struct {
	ID        string
	Harness   string
	CreatedAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.Harness, arg.CreatedAt)
	return err
}

const eventSeqsFrom = `-- name: EventSeqsFrom :many

SELECT seq FROM events WHERE run_id = ?1 AND seq > ?2 ORDER BY seq LIMIT ?3
`

type EventSeqsFromParams struct {
	RunID string
	After int64
	Max   int64
}

// Events and results (DEV-6): the protocol's two reporting calls.
func (q *Queries) EventSeqsFrom(ctx context.Context, arg EventSeqsFromParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, eventSeqsFrom, arg.RunID, arg.After, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var seq int64
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsAfter = `-- name: EventsAfter :many
SELECT seq, body FROM events WHERE run_id = ? AND seq > ? ORDER BY seq LIMIT ?
`

type EventsAfterParams struct {
	RunID string
	Seq   int64
	Limit int64
}

type EventsAfterRow struct {
	Seq  int64
	Body string
}

func (q *Queries) EventsAfter(ctx context.Context, arg EventsAfterParams) ([]EventsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, eventsAfter, arg.RunID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsAfterRow{}
	for rows.Next() {
		var i EventsAfterRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishRun = `-- name: FinishRun :exec
UPDATE runs SET state = ?, reason = ?, lease_expires_at = NULL, resumes_at = NULL, updated_at = ?
WHERE id = ?
`

type FinishRunParams struct {
	State     string
	Reason    sql.NullString
	UpdatedAt int64
	ID        string
}

// The result settles the run: its state, the reason a failure gave, and no
// lease any more, so a finished run cannot lapse into lost.
func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.State,
		arg.Reason,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const getAdminToken = `-- name: GetAdminToken :one
SELECT hash, name, created_at FROM admin_tokens WHERE hash = ?
`

func (q *Queries) GetAdminToken(ctx context.Context, hash string) (AdminToken, error) {
	row := q.db.QueryRowContext(ctx, getAdminToken, hash)
	var i AdminToken
	err := row.Scan(&i.Hash, &i.Name, &i.CreatedAt)
	return i, err
}

const getRegistrationToken = `-- name: GetRegistrationToken :one
SELECT hash, created_at, expires_at, for_runner, used_at, runner_id FROM registration_tokens WHERE hash = ?
`

func (q *Queries) GetRegistrationToken(ctx context.Context, hash string) (RegistrationToken, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationToken, hash)
	var i RegistrationToken
	err := row.Scan(
		&i.Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ForRunner,
		&i.UsedAt,
		&i.RunnerID,
	)
	return i, err
}

const getResult = `-- name: GetResult :one
SELECT run_id, state, body, received_at FROM results WHERE run_id = ?
`

func (q *Queries) GetResult(ctx context.Context, runID string) (Result, error) {
	row := q.db.QueryRowContext(ctx, getResult, runID)
	var i Result
	err := row.Scan(
		&i.RunID,
		&i.State,
		&i.Body,
		&i.ReceivedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, session_id, harness, model, spec, state, runner_id, lease_expires_at, resumes_at, reason, created_at, updated_at, events_through FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Harness,
		&i.Model,
		&i.Spec,
		&i.State,
		&i.RunnerID,
		&i.LeaseExpiresAt,
		&i.ResumesAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventsThrough,
	)
	return i, err
}

const getRunner = `-- name: GetRunner :one
SELECT id, name, credential_hash, capabilities, fingerprint, wants_capabilities, health, registered_at, last_sync_at FROM runners WHERE id = ?
`

func (q *Queries) GetRunner(ctx context.Context, id string) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunner, id)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialHash,
		&i.Capabilities,
		&i.Fingerprint,
		&i.WantsCapabilities,
		&i.Health,
		&i.RegisteredAt,
		&i.LastSyncAt,
	)
	return i, err
}

const getRunnerByCredential = `-- name: GetRunnerByCredential :one
SELECT id, name, credential_hash, capabilities, fingerprint, wants_capabilities, health, registered_at, last_sync_at FROM runners WHERE credential_hash = ?
`

func (q *Queries) GetRunnerByCredential(ctx context.Context, credentialHash string) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunnerByCredential, credentialHash)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialHash,
		&i.Capabilities,
		&i.Fingerprint,
		&i.WantsCapabilities,
		&i.Health,
		&i.RegisteredAt,
		&i.LastSyncAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, harness, runner_id, created_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Harness,
		&i.RunnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminTokens = `-- name: ListAdminTokens :many
SELECT name, created_at FROM admin_tokens ORDER BY name
`

type ListAdminTokensRow struct {
	Name      string
	CreatedAt int64
}

func (q *Queries) ListAdminTokens(ctx context.Context) ([]ListAdminTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminTokensRow{}
	for rows.Next() {
		var i ListAdminTokensRow
		if err := rows.Scan(&i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loseLapsedRuns = `-- name: LoseLapsedRuns :execrows
UPDATE runs SET state = 'lost', reason = 'the runner stopped syncing and its lease lapsed', updated_at = ?1
WHERE state IN ('claimed', 'preparing', 'running', 'waiting') AND lease_expires_at <= ?1
`

func (q *Queries) LoseLapsedRuns(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, loseLapsedRuns, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const offerCandidates = `-- name: OfferCandidates :many
SELECT r.id, r.session_id, r.harness, r.model, r.spec, r.state, r.runner_id, r.lease_expires_at, r.resumes_at, r.reason, r.created_at, r.updated_at, r.events_through FROM runs r JOIN sessions s ON s.id = r.session_id
WHERE r.state = 'queued'
  AND r.harness IN (SELECT value FROM json_each(?1))
  AND (r.created_at > ?2 OR (r.created_at = ?2 AND r.id > ?3))
  AND (s.runner_id IS NULL OR s.runner_id = ?4)
  AND NOT EXISTS (
      SELECT 1 FROM runs o
      WHERE o.session_id = r.session_id
        AND o.state IN ('offered', 'claimed', 'preparing', 'running', 'waiting'))
  AND NOT EXISTS (
      SELECT 1 FROM runs e
      WHERE e.session_id = r.session_id AND e.state = 'queued'
        AND (e.created_at < r.created_at OR (e.created_at = r.created_at AND e.id < r.id)))
ORDER BY r.created_at, r.id
LIMIT ?5
`

type OfferCandidatesParams struct {
	HarnessesJson  interface{}
	AfterCreatedAt int64
	AfterID        string
	RunnerID       sql.NullString
	Max            int64
}

// Queued runs this runner may be offered, oldest first, a page at a time
// after the (created_at, id) cursor: only harnesses it can take now, only the
// oldest queued run of each session, only in a session that is unbound or
// bound to it, and never while another run of that session is out, since a
// session has at most one live run. Filtering here rather than in Go is what
// keeps runs it must skip from filling the page ahead of runs it could take.
func (q *Queries) OfferCandidates(ctx context.Context, arg OfferCandidatesParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, offerCandidates,
		arg.HarnessesJson,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RunnerID,
		arg.Max,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.Spec,
			&i.State,
			&i.RunnerID,
			&i.LeaseExpiresAt,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventsThrough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offerRun = `-- name: OfferRun :exec
UPDATE runs SET state = 'offered', runner_id = ?, lease_expires_at = ?, updated_at = ?
WHERE id = ? AND state = 'queued'
`

type OfferRunParams struct {
	RunnerID       sql.NullString
	LeaseExpiresAt sql.NullInt64
	UpdatedAt      int64
	ID             string
}

func (q *Queries) OfferRun(ctx context.Context, arg OfferRunParams) error {
	_, err := q.db.ExecContext(ctx, offerRun,
		arg.RunnerID,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const putResult = `-- name: PutResult :execrows
INSERT INTO results (run_id, state, body, received_at) VALUES (?, ?, ?, ?)
ON CONFLICT (run_id) DO NOTHING
`

type PutResultParams struct {
	RunID      string
	State      string
	Body       string
	ReceivedAt int64
}

func (q *Queries) PutResult(ctx context.Context, arg PutResultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, putResult,
		arg.RunID,
		arg.State,
		arg.Body,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordSync = `-- name: RecordSync :exec
UPDATE runners SET last_sync_at = ?, health = ?, wants_capabilities = ? WHERE id = ?
`

type RecordSyncParams struct {
	LastSyncAt        sql.NullInt64
	Health            sql.NullString
	WantsCapabilities int64
	ID                string
}

func (q *Queries) RecordSync(ctx context.Context, arg RecordSyncParams) error {
	_, err := q.db.ExecContext(ctx, recordSync,
		arg.LastSyncAt,
		arg.Health,
		arg.WantsCapabilities,
		arg.ID,
	)
	return err
}

const renewRun = `-- name: RenewRun :exec
UPDATE runs SET state = ?, lease_expires_at = ?, resumes_at = ?, reason = ?, updated_at = ?
WHERE id = ? AND runner_id = ?
`

type RenewRunParams struct {
	State          string
	LeaseExpiresAt sql.NullInt64
	ResumesAt      sql.NullInt64
	Reason         sql.NullString
	UpdatedAt      int64
	ID             string
	RunnerID       sql.NullString
}

// Listing a run claims it (when offered) and renews its lease (always).
func (q *Queries) RenewRun(ctx context.Context, arg RenewRunParams) error {
	_, err := q.db.ExecContext(ctx, renewRun,
		arg.State,
		arg.LeaseExpiresAt,
		arg.ResumesAt,
		arg.Reason,
		arg.UpdatedAt,
		arg.ID,
		arg.RunnerID,
	)
	return err
}

const requeueRun = `-- name: RequeueRun :exec
UPDATE runs SET state = 'queued', runner_id = NULL, lease_expires_at = NULL, updated_at = ?
WHERE id = ? AND state = 'offered'
`

type RequeueRunParams struct {
	UpdatedAt int64
	ID        string
}

// An offer the runner did not list back was never received: the run goes back
// in the queue, for this runner or another.
func (q *Queries) RequeueRun(ctx context.Context, arg RequeueRunParams) error {
	_, err := q.db.ExecContext(ctx, requeueRun, arg.UpdatedAt, arg.ID)
	return err
}

const requeueWithdrawnOffers = `-- name: RequeueWithdrawnOffers :execrows
UPDATE runs SET state = 'queued', runner_id = NULL, lease_expires_at = NULL, updated_at = ?1
WHERE state = 'offered' AND lease_expires_at <= ?1
`

func (q *Queries) RequeueWithdrawnOffers(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueWithdrawnOffers, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAdminToken = `-- name: RevokeAdminToken :execrows
DELETE FROM admin_tokens WHERE name = ?
`

func (q *Queries) RevokeAdminToken(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAdminToken, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const runsOfferedTo = `-- name: RunsOfferedTo :many
SELECT id, session_id, harness, model, spec, state, runner_id, lease_expires_at, resumes_at, reason, created_at, updated_at, events_through FROM runs WHERE runner_id = ? AND state = 'offered'
`

func (q *Queries) RunsOfferedTo(ctx context.Context, runnerID sql.NullString) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, runsOfferedTo, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.Spec,
			&i.State,
			&i.RunnerID,
			&i.LeaseExpiresAt,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventsThrough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCapabilities = `-- name: SetCapabilities :exec
UPDATE runners SET capabilities = ?, fingerprint = ?, wants_capabilities = 0 WHERE id = ?
`

type SetCapabilitiesParams struct {
	Capabilities string
	Fingerprint  string
	ID           string
}

func (q *Queries) SetCapabilities(ctx context.Context, arg SetCapabilitiesParams) error {
	_, err := q.db.ExecContext(ctx, setCapabilities, arg.Capabilities, arg.Fingerprint, arg.ID)
	return err
}

const setEventsThrough = `-- name: SetEventsThrough :exec
UPDATE runs SET events_through = ? WHERE id = ?
`

type SetEventsThroughParams struct {
	EventsThrough int64
	ID            string
}

func (q *Queries) SetEventsThrough(ctx context.Context, arg SetEventsThroughParams) error {
	_, err := q.db.ExecContext(ctx, setEventsThrough, arg.EventsThrough, arg.ID)
	return err
}

const upsertRunner = `-- name: UpsertRunner :exec
INSERT INTO runners (id, name, credential_hash, capabilities, fingerprint, registered_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    credential_hash = excluded.credential_hash,
    capabilities = excluded.capabilities,
    fingerprint = excluded.fingerprint,
    wants_capabilities = 0,
    registered_at = excluded.registered_at
`

type UpsertRunnerParams struct {
	ID             string
	Name           string
	CredentialHash string
	Capabilities   string
	Fingerprint    string
	RegisteredAt   int64
}

// Registering an id that exists replaces its credential: the old one dies,
// which is how a runner that lost its credential file is recovered. The
// caller checks the token was issued for that id first.
func (q *Queries) UpsertRunner(ctx context.Context, arg UpsertRunnerParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunner,
		arg.ID,
		arg.Name,
		arg.CredentialHash,
		arg.Capabilities,
		arg.Fingerprint,
		arg.RegisteredAt,
	)
	return err
}
