// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const addControl = `-- name: AddControl :exec

INSERT INTO run_controls (run_id, kind, text, created_at) VALUES (?, ?, ?, ?)
`

type AddControlParams struct {
	RunID     string
	Kind      string
	Text      string
	CreatedAt int64
}

// Cancel, interrupt and steer (DEV-8).
func (q *Queries) AddControl(ctx context.Context, arg AddControlParams) error {
	_, err := q.db.ExecContext(ctx, addControl,
		arg.RunID,
		arg.Kind,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}

const appendEvent = `-- name: AppendEvent :execrows
INSERT INTO events (run_id, seq, body, received_at) VALUES (?, ?, ?, ?)
ON CONFLICT (run_id, seq) DO NOTHING
`

type AppendEventParams struct {
	RunID      string
	Seq        int64
	Body       string
	ReceivedAt int64
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, appendEvent,
		arg.RunID,
		arg.Seq,
		arg.Body,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindSession = `-- name: BindSession :exec
UPDATE sessions SET runner_id = ? WHERE id = ? AND runner_id IS NULL
`

type BindSessionParams struct {
	RunnerID sql.NullString
	ID       string
}

// The first claim in a session binds it; later ones leave it as it is.
func (q *Queries) BindSession(ctx context.Context, arg BindSessionParams) error {
	_, err := q.db.ExecContext(ctx, bindSession, arg.RunnerID, arg.ID)
	return err
}

const burnRegistrationToken = `-- name: BurnRegistrationToken :execrows
UPDATE registration_tokens SET used_at = ?1, runner_id = ?2
WHERE hash = ?3 AND used_at IS NULL AND expires_at > ?1
`

type BurnRegistrationTokenParams struct {
	Now      sql.NullInt64
	RunnerID sql.NullString
	Hash     string
}

// Burning is one conditional update, so two exchanges racing on one token
// cannot both see it unused.
func (q *Queries) BurnRegistrationToken(ctx context.Context, arg BurnRegistrationTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, burnRegistrationToken, arg.Now, arg.RunnerID, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearDrain = `-- name: ClearDrain :exec
UPDATE runners SET drain_requested_at = NULL WHERE id = ?
`

func (q *Queries) ClearDrain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearDrain, id)
	return err
}

const closeSessionHere = `-- name: CloseSessionHere :execrows
UPDATE sessions SET closed_at = ?1, close_reason = ?2, close_requested_at = NULL
WHERE id = ?3 AND closed_at IS NULL
`

type CloseSessionHereParams struct {
	Now    sql.NullInt64
	Reason sql.NullString
	ID     string
}

// The hub closing a session by its own act (decision 0011), with no runner
// to report it: one nobody ever claimed, or one whose runner deregistered.
// The caller has decided no runner's close is owed; a repeat changes nothing.
func (q *Queries) CloseSessionHere(ctx context.Context, arg CloseSessionHereParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeSessionHere, arg.Now, arg.Reason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const controlsFor = `-- name: ControlsFor :many
SELECT id, run_id, kind, text, created_at FROM run_controls WHERE run_id = ? ORDER BY id
`

func (q *Queries) ControlsFor(ctx context.Context, runID string) ([]RunControl, error) {
	rows, err := q.db.QueryContext(ctx, controlsFor, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunControl{}
	for rows.Next() {
		var i RunControl
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAdminToken = `-- name: CreateAdminToken :exec

INSERT INTO admin_tokens (hash, name, created_at) VALUES (?, ?, ?)
`

type CreateAdminTokenParams struct {
	Hash      string
	Name      string
	CreatedAt int64
}

// Admin tokens and the service API (DEV-7). Kept in one block so the runner's
// events and result queries can land beside it without a merge fight.
func (q *Queries) CreateAdminToken(ctx context.Context, arg CreateAdminTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAdminToken, arg.Hash, arg.Name, arg.CreatedAt)
	return err
}

const createRegistrationToken = `-- name: CreateRegistrationToken :exec
INSERT INTO registration_tokens (hash, created_at, expires_at, for_runner) VALUES (?, ?, ?, ?)
`

type CreateRegistrationTokenParams struct {
	Hash      string
	CreatedAt int64
	ExpiresAt int64
	ForRunner sql.NullString
}

func (q *Queries) CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRegistrationToken,
		arg.Hash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ForRunner,
	)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, session_id, harness, model, spec, state, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'queued', ?, ?)
`

type CreateRunParams struct {
	ID        string
	SessionID string
	Harness   string
	Model     string
	Spec      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.SessionID,
		arg.Harness,
		arg.Model,
		arg.Spec,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, harness, created_at) VALUES (?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type CreateSessionParams struct {
	ID        string
	Harness   string
	CreatedAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.Harness, arg.CreatedAt)
	return err
}

const deleteSteersThrough = `-- name: DeleteSteersThrough :exec
DELETE FROM run_controls WHERE run_id = ? AND kind = 'steer' AND id <= ?
`

type DeleteSteersThroughParams struct {
	RunID string
	ID    int64
}

func (q *Queries) DeleteSteersThrough(ctx context.Context, arg DeleteSteersThroughParams) error {
	_, err := q.db.ExecContext(ctx, deleteSteersThrough, arg.RunID, arg.ID)
	return err
}

const endUnstartedRun = `-- name: EndUnstartedRun :execrows
UPDATE runs SET state = ?1, reason = ?2, lease_expires_at = NULL, updated_at = ?3
WHERE id = ?4 AND state IN ('queued', 'offered')
`

type EndUnstartedRunParams struct {
	State  string
	Reason sql.NullString
	Now    int64
	ID     string
}

// A run no runner has started ends on the hub alone: cancelled when someone
// asked, failed when what it needed has gone. An offered run keeps its
// runner: that runner lists it once more, hears cancel, and withdraws it.
func (q *Queries) EndUnstartedRun(ctx context.Context, arg EndUnstartedRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, endUnstartedRun,
		arg.State,
		arg.Reason,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const eventSeqsFrom = `-- name: EventSeqsFrom :many

SELECT seq FROM events WHERE run_id = ?1 AND seq > ?2 ORDER BY seq LIMIT ?3
`

type EventSeqsFromParams struct {
	RunID string
	After int64
	Max   int64
}

// Events and results (DEV-6): the protocol's two reporting calls.
func (q *Queries) EventSeqsFrom(ctx context.Context, arg EventSeqsFromParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, eventSeqsFrom, arg.RunID, arg.After, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var seq int64
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsAfter = `-- name: EventsAfter :many
SELECT seq, body FROM events WHERE run_id = ? AND seq > ? ORDER BY seq LIMIT ?
`

type EventsAfterParams struct {
	RunID string
	Seq   int64
	Limit int64
}

type EventsAfterRow struct {
	Seq  int64
	Body string
}

func (q *Queries) EventsAfter(ctx context.Context, arg EventsAfterParams) ([]EventsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, eventsAfter, arg.RunID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsAfterRow{}
	for rows.Next() {
		var i EventsAfterRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsContiguous = `-- name: EventsContiguous :many
SELECT e.seq, e.body FROM events e JOIN runs r ON r.id = e.run_id
WHERE e.run_id = ?1 AND e.seq > ?2 AND e.seq <= r.events_through
ORDER BY e.seq LIMIT ?3
`

type EventsContiguousParams struct {
	RunID string
	After int64
	Max   int64
}

type EventsContiguousRow struct {
	Seq  int64
	Body string
}

// A watcher reads only as far as the stream is contiguous: an event stored
// past a gap waits until the gap is filled, or a cursor would move past the
// missing seq and never see it.
func (q *Queries) EventsContiguous(ctx context.Context, arg EventsContiguousParams) ([]EventsContiguousRow, error) {
	rows, err := q.db.QueryContext(ctx, eventsContiguous, arg.RunID, arg.After, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsContiguousRow{}
	for rows.Next() {
		var i EventsContiguousRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishRun = `-- name: FinishRun :exec
UPDATE runs SET state = ?, reason = ?, lease_expires_at = NULL, resumes_at = NULL, updated_at = ?
WHERE id = ?
`

type FinishRunParams struct {
	State     string
	Reason    sql.NullString
	UpdatedAt int64
	ID        string
}

// The result settles the run: its state, the reason a failure gave, and no
// lease any more, so a finished run cannot lapse into lost.
func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.State,
		arg.Reason,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const firstControl = `-- name: FirstControl :one
SELECT id, run_id, kind, text, created_at FROM run_controls WHERE run_id = ? AND kind = ? ORDER BY id LIMIT 1
`

type FirstControlParams struct {
	RunID string
	Kind  string
}

func (q *Queries) FirstControl(ctx context.Context, arg FirstControlParams) (RunControl, error) {
	row := q.db.QueryRowContext(ctx, firstControl, arg.RunID, arg.Kind)
	var i RunControl
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminToken = `-- name: GetAdminToken :one
SELECT hash, name, created_at FROM admin_tokens WHERE hash = ?
`

func (q *Queries) GetAdminToken(ctx context.Context, hash string) (AdminToken, error) {
	row := q.db.QueryRowContext(ctx, getAdminToken, hash)
	var i AdminToken
	err := row.Scan(&i.Hash, &i.Name, &i.CreatedAt)
	return i, err
}

const getRegistrationToken = `-- name: GetRegistrationToken :one
SELECT hash, created_at, expires_at, for_runner, used_at, runner_id FROM registration_tokens WHERE hash = ?
`

func (q *Queries) GetRegistrationToken(ctx context.Context, hash string) (RegistrationToken, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationToken, hash)
	var i RegistrationToken
	err := row.Scan(
		&i.Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ForRunner,
		&i.UsedAt,
		&i.RunnerID,
	)
	return i, err
}

const getResult = `-- name: GetResult :one
SELECT run_id, state, body, received_at FROM results WHERE run_id = ?
`

func (q *Queries) GetResult(ctx context.Context, runID string) (Result, error) {
	row := q.db.QueryRowContext(ctx, getResult, runID)
	var i Result
	err := row.Scan(
		&i.RunID,
		&i.State,
		&i.Body,
		&i.ReceivedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, session_id, harness, model, spec, state, runner_id, lease_expires_at, resumes_at, reason, created_at, updated_at, events_through FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Harness,
		&i.Model,
		&i.Spec,
		&i.State,
		&i.RunnerID,
		&i.LeaseExpiresAt,
		&i.ResumesAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventsThrough,
	)
	return i, err
}

const getRunner = `-- name: GetRunner :one
SELECT id, name, credential_hash, capabilities, fingerprint, wants_capabilities, health, registered_at, last_sync_at, drain_requested_at FROM runners WHERE id = ?
`

func (q *Queries) GetRunner(ctx context.Context, id string) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunner, id)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialHash,
		&i.Capabilities,
		&i.Fingerprint,
		&i.WantsCapabilities,
		&i.Health,
		&i.RegisteredAt,
		&i.LastSyncAt,
		&i.DrainRequestedAt,
	)
	return i, err
}

const getRunnerByCredential = `-- name: GetRunnerByCredential :one
SELECT id, name, credential_hash, capabilities, fingerprint, wants_capabilities, health, registered_at, last_sync_at, drain_requested_at FROM runners WHERE credential_hash = ?
`

func (q *Queries) GetRunnerByCredential(ctx context.Context, credentialHash string) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunnerByCredential, credentialHash)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialHash,
		&i.Capabilities,
		&i.Fingerprint,
		&i.WantsCapabilities,
		&i.Health,
		&i.RegisteredAt,
		&i.LastSyncAt,
		&i.DrainRequestedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, harness, runner_id, created_at, close_requested_at, closed_at, close_reason, offered_to FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Harness,
		&i.RunnerID,
		&i.CreatedAt,
		&i.CloseRequestedAt,
		&i.ClosedAt,
		&i.CloseReason,
		&i.OfferedTo,
	)
	return i, err
}

const listAdminTokens = `-- name: ListAdminTokens :many
SELECT name, created_at FROM admin_tokens ORDER BY name
`

type ListAdminTokensRow struct {
	Name      string
	CreatedAt int64
}

func (q *Queries) ListAdminTokens(ctx context.Context) ([]ListAdminTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminTokensRow{}
	for rows.Next() {
		var i ListAdminTokensRow
		if err := rows.Scan(&i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunners = `-- name: ListRunners :many
SELECT id, name, credential_hash, capabilities, fingerprint, wants_capabilities, health, registered_at, last_sync_at, drain_requested_at FROM runners ORDER BY last_sync_at IS NULL, last_sync_at DESC, id
`

// Every runner this hub knows. The ones still talking to it come first, so an
// operator reading the list sees the live fleet before the retired machines;
// a runner that registered and never synced sorts last, by id.
func (q *Queries) ListRunners(ctx context.Context) ([]Runner, error) {
	rows, err := q.db.QueryContext(ctx, listRunners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Runner{}
	for rows.Next() {
		var i Runner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CredentialHash,
			&i.Capabilities,
			&i.Fingerprint,
			&i.WantsCapabilities,
			&i.Health,
			&i.RegisteredAt,
			&i.LastSyncAt,
			&i.DrainRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loseLapsedRuns = `-- name: LoseLapsedRuns :execrows
UPDATE runs SET state = 'lost', reason = 'the runner stopped syncing and its lease lapsed', updated_at = ?1
WHERE state IN ('claimed', 'preparing', 'running', 'waiting') AND lease_expires_at <= ?1
`

func (q *Queries) LoseLapsedRuns(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, loseLapsedRuns, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const loseRunnerRuns = `-- name: LoseRunnerRuns :execrows
UPDATE runs SET state = 'lost', reason = ?1, lease_expires_at = NULL, resumes_at = NULL,
  updated_at = ?2
WHERE runner_id = ?3 AND state IN ('claimed', 'preparing', 'running', 'waiting')
`

type LoseRunnerRunsParams struct {
	Reason   sql.NullString
	Now      int64
	RunnerID sql.NullString
}

// Runs a departed runner held are lost: it is not coming back to report
// them, and lost is what a hub tells a submitter then (decision 0023).
func (q *Queries) LoseRunnerRuns(ctx context.Context, arg LoseRunnerRunsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, loseRunnerRuns, arg.Reason, arg.Now, arg.RunnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const noteSessionOffer = `-- name: NoteSessionOffer :exec
UPDATE sessions SET offered_to = ?1 WHERE id = ?2 AND runner_id IS NULL
`

type NoteSessionOfferParams struct {
	RunnerID sql.NullString
	ID       string
}

// Until a claim binds it, a session remembers the runner its run was last
// offered to: the one runner whose report of closing it is believed.
func (q *Queries) NoteSessionOffer(ctx context.Context, arg NoteSessionOfferParams) error {
	_, err := q.db.ExecContext(ctx, noteSessionOffer, arg.RunnerID, arg.ID)
	return err
}

const offerCandidates = `-- name: OfferCandidates :many
SELECT r.id, r.session_id, r.harness, r.model, r.spec, r.state, r.runner_id, r.lease_expires_at, r.resumes_at, r.reason, r.created_at, r.updated_at, r.events_through FROM runs r JOIN sessions s ON s.id = r.session_id
WHERE r.state = 'queued'
  AND r.harness IN (SELECT value FROM json_each(?1))
  AND (r.created_at > ?2 OR (r.created_at = ?2 AND r.id > ?3))
  AND (s.runner_id IS NULL OR s.runner_id = ?4)
  AND NOT EXISTS (
      SELECT 1 FROM runs o
      WHERE o.session_id = r.session_id
        AND o.state IN ('offered', 'claimed', 'preparing', 'running', 'waiting'))
  AND NOT EXISTS (
      SELECT 1 FROM runs e
      WHERE e.session_id = r.session_id AND e.state = 'queued'
        AND (e.created_at < r.created_at OR (e.created_at = r.created_at AND e.id < r.id)))
ORDER BY r.created_at, r.id
LIMIT ?5
`

type OfferCandidatesParams struct {
	HarnessesJson  interface{}
	AfterCreatedAt int64
	AfterID        string
	RunnerID       sql.NullString
	Max            int64
}

// Queued runs this runner may be offered, oldest first, a page at a time
// after the (created_at, id) cursor: only harnesses it can take now, only the
// oldest queued run of each session, only in a session that is unbound or
// bound to it, and never while another run of that session is out, since a
// session has at most one live run. Filtering here rather than in Go is what
// keeps runs it must skip from filling the page ahead of runs it could take.
func (q *Queries) OfferCandidates(ctx context.Context, arg OfferCandidatesParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, offerCandidates,
		arg.HarnessesJson,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RunnerID,
		arg.Max,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.Spec,
			&i.State,
			&i.RunnerID,
			&i.LeaseExpiresAt,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventsThrough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offerRun = `-- name: OfferRun :exec
UPDATE runs SET state = 'offered', runner_id = ?, lease_expires_at = ?, updated_at = ?
WHERE id = ? AND state = 'queued'
`

type OfferRunParams struct {
	RunnerID       sql.NullString
	LeaseExpiresAt sql.NullInt64
	UpdatedAt      int64
	ID             string
}

func (q *Queries) OfferRun(ctx context.Context, arg OfferRunParams) error {
	_, err := q.db.ExecContext(ctx, offerRun,
		arg.RunnerID,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const putResult = `-- name: PutResult :execrows
INSERT INTO results (run_id, state, body, received_at) VALUES (?, ?, ?, ?)
ON CONFLICT (run_id) DO NOTHING
`

type PutResultParams struct {
	RunID      string
	State      string
	Body       string
	ReceivedAt int64
}

func (q *Queries) PutResult(ctx context.Context, arg PutResultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, putResult,
		arg.RunID,
		arg.State,
		arg.Body,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordSessionClosed = `-- name: RecordSessionClosed :execrows
UPDATE sessions SET closed_at = ?1, close_reason = ?2, close_requested_at = NULL,
  runner_id = ?3
WHERE id = ?4 AND closed_at IS NULL
  AND (runner_id = ?3 OR (runner_id IS NULL AND offered_to = ?3))
`

type RecordSessionClosedParams struct {
	ClosedAt sql.NullInt64
	Reason   sql.NullString
	RunnerID sql.NullString
	ID       string
}

// A runner's report closes a session bound to it, or an unbound one whose
// run was last offered to it: its claim may have been withdrawn before any
// sync listed it, and the close its owner asked for meanwhile is still owed
// (DEV-103). Such a session is bound to the reporter as it closes, since
// whatever it left is on that runner's disk. A repeat changes nothing, and a
// report from any other runner is not applied.
func (q *Queries) RecordSessionClosed(ctx context.Context, arg RecordSessionClosedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordSessionClosed,
		arg.ClosedAt,
		arg.Reason,
		arg.RunnerID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordSync = `-- name: RecordSync :exec
UPDATE runners SET last_sync_at = ?, health = ?, wants_capabilities = ? WHERE id = ?
`

type RecordSyncParams struct {
	LastSyncAt        sql.NullInt64
	Health            sql.NullString
	WantsCapabilities int64
	ID                string
}

func (q *Queries) RecordSync(ctx context.Context, arg RecordSyncParams) error {
	_, err := q.db.ExecContext(ctx, recordSync,
		arg.LastSyncAt,
		arg.Health,
		arg.WantsCapabilities,
		arg.ID,
	)
	return err
}

const renewRun = `-- name: RenewRun :exec
UPDATE runs SET state = ?, lease_expires_at = ?, resumes_at = ?, reason = ?, updated_at = ?
WHERE id = ? AND runner_id = ?
`

type RenewRunParams struct {
	State          string
	LeaseExpiresAt sql.NullInt64
	ResumesAt      sql.NullInt64
	Reason         sql.NullString
	UpdatedAt      int64
	ID             string
	RunnerID       sql.NullString
}

// Listing a run claims it (when offered) and renews its lease (always).
func (q *Queries) RenewRun(ctx context.Context, arg RenewRunParams) error {
	_, err := q.db.ExecContext(ctx, renewRun,
		arg.State,
		arg.LeaseExpiresAt,
		arg.ResumesAt,
		arg.Reason,
		arg.UpdatedAt,
		arg.ID,
		arg.RunnerID,
	)
	return err
}

const requestDrain = `-- name: RequestDrain :exec
UPDATE runners SET drain_requested_at = COALESCE(drain_requested_at, ?1) WHERE id = ?2
`

type RequestDrainParams struct {
	Now sql.NullInt64
	ID  string
}

func (q *Queries) RequestDrain(ctx context.Context, arg RequestDrainParams) error {
	_, err := q.db.ExecContext(ctx, requestDrain, arg.Now, arg.ID)
	return err
}

const requestSessionClose = `-- name: RequestSessionClose :exec
UPDATE sessions SET close_requested_at = COALESCE(close_requested_at, ?1)
WHERE id = ?2 AND closed_at IS NULL
`

type RequestSessionCloseParams struct {
	Now sql.NullInt64
	ID  string
}

func (q *Queries) RequestSessionClose(ctx context.Context, arg RequestSessionCloseParams) error {
	_, err := q.db.ExecContext(ctx, requestSessionClose, arg.Now, arg.ID)
	return err
}

const requeueRun = `-- name: RequeueRun :exec
UPDATE runs SET state = 'queued', runner_id = NULL, lease_expires_at = NULL, updated_at = ?
WHERE id = ? AND state = 'offered'
`

type RequeueRunParams struct {
	UpdatedAt int64
	ID        string
}

// An offer the runner did not list back was never received: the run goes back
// in the queue, for this runner or another.
func (q *Queries) RequeueRun(ctx context.Context, arg RequeueRunParams) error {
	_, err := q.db.ExecContext(ctx, requeueRun, arg.UpdatedAt, arg.ID)
	return err
}

const requeueRunnerOffers = `-- name: RequeueRunnerOffers :execrows
UPDATE runs SET state = 'queued', runner_id = NULL, lease_expires_at = NULL, updated_at = ?1
WHERE runner_id = ?2 AND state = 'offered'
`

type RequeueRunnerOffersParams struct {
	Now      int64
	RunnerID sql.NullString
}

// An offer it never claimed was never held, so it goes back in the queue
// rather than being lost.
func (q *Queries) RequeueRunnerOffers(ctx context.Context, arg RequeueRunnerOffersParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueRunnerOffers, arg.Now, arg.RunnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueWithdrawnOffers = `-- name: RequeueWithdrawnOffers :execrows
UPDATE runs SET state = 'queued', runner_id = NULL, lease_expires_at = NULL, updated_at = ?1
WHERE state = 'offered' AND lease_expires_at <= ?1
`

func (q *Queries) RequeueWithdrawnOffers(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueWithdrawnOffers, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retireRunnerCredential = `-- name: RetireRunnerCredential :exec
UPDATE runners SET credential_hash = ?1, drain_requested_at = NULL
WHERE id = ?2
`

type RetireRunnerCredentialParams struct {
	CredentialHash string
	ID             string
}

// Deregistration. A runner that deregisters keeps its row: sessions and runs
// reference it, and re-registering under a token issued for that id is how it
// comes back. What goes is its credential, replaced by the hash of a secret
// nobody was given, so nothing can authenticate as it again.
func (q *Queries) RetireRunnerCredential(ctx context.Context, arg RetireRunnerCredentialParams) error {
	_, err := q.db.ExecContext(ctx, retireRunnerCredential, arg.CredentialHash, arg.ID)
	return err
}

const revokeAdminToken = `-- name: RevokeAdminToken :execrows
DELETE FROM admin_tokens WHERE name = ?
`

func (q *Queries) RevokeAdminToken(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAdminToken, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const runsOfferedTo = `-- name: RunsOfferedTo :many
SELECT id, session_id, harness, model, spec, state, runner_id, lease_expires_at, resumes_at, reason, created_at, updated_at, events_through FROM runs WHERE runner_id = ? AND state = 'offered'
`

func (q *Queries) RunsOfferedTo(ctx context.Context, runnerID sql.NullString) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, runsOfferedTo, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.Spec,
			&i.State,
			&i.RunnerID,
			&i.LeaseExpiresAt,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventsThrough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionsToClose = `-- name: SessionsToClose :many
SELECT id FROM sessions WHERE runner_id = ? AND close_requested_at IS NOT NULL AND closed_at IS NULL ORDER BY id
`

func (q *Queries) SessionsToClose(ctx context.Context, runnerID sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, sessionsToClose, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionsToSettle = `-- name: SessionsToSettle :many
SELECT id FROM sessions WHERE runner_id = ?1 AND closed_at IS NULL ORDER BY id
`

// A departed runner's sessions that still need the hub: the open ones. A
// closed one holds no waiting run, because every close ends those.
func (q *Queries) SessionsToSettle(ctx context.Context, runnerID sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, sessionsToSettle, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCapabilities = `-- name: SetCapabilities :exec
UPDATE runners SET capabilities = ?, fingerprint = ?, wants_capabilities = 0 WHERE id = ?
`

type SetCapabilitiesParams struct {
	Capabilities string
	Fingerprint  string
	ID           string
}

func (q *Queries) SetCapabilities(ctx context.Context, arg SetCapabilitiesParams) error {
	_, err := q.db.ExecContext(ctx, setCapabilities, arg.Capabilities, arg.Fingerprint, arg.ID)
	return err
}

const setEventsThrough = `-- name: SetEventsThrough :exec
UPDATE runs SET events_through = ? WHERE id = ?
`

type SetEventsThroughParams struct {
	EventsThrough int64
	ID            string
}

func (q *Queries) SetEventsThrough(ctx context.Context, arg SetEventsThroughParams) error {
	_, err := q.db.ExecContext(ctx, setEventsThrough, arg.EventsThrough, arg.ID)
	return err
}

const unstartedRunsInSession = `-- name: UnstartedRunsInSession :many
SELECT id FROM runs WHERE session_id = ? AND state IN ('queued', 'offered') ORDER BY created_at, id
`

func (q *Queries) UnstartedRunsInSession(ctx context.Context, sessionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, unstartedRunsInSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRunner = `-- name: UpsertRunner :exec
INSERT INTO runners (id, name, credential_hash, capabilities, fingerprint, registered_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    credential_hash = excluded.credential_hash,
    capabilities = excluded.capabilities,
    fingerprint = excluded.fingerprint,
    wants_capabilities = 0,
    registered_at = excluded.registered_at
`

type UpsertRunnerParams struct {
	ID             string
	Name           string
	CredentialHash string
	Capabilities   string
	Fingerprint    string
	RegisteredAt   int64
}

// Registering an id that exists replaces its credential: the old one dies,
// which is how a runner that lost its credential file is recovered. The
// caller checks the token was issued for that id first.
func (q *Queries) UpsertRunner(ctx context.Context, arg UpsertRunnerParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunner,
		arg.ID,
		arg.Name,
		arg.CredentialHash,
		arg.Capabilities,
		arg.Fingerprint,
		arg.RegisteredAt,
	)
	return err
}
