// Package store is yad hub's durable state: registration tokens, runners,
// sessions, runs, events and results — one SQLite file, separate from any
// runner's state.db.
//
// It is opened exactly as the runner's store is (store.OpenSQLite), with its
// own migrations; the queries live in queries.sql and the Go in db/ is
// generated by sqlc and committed.
package store

import (
	"context"
	"database/sql"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	v1 "github.com/skkap/yad/protocol/v1"

	"github.com/skkap/yad/internal/hub/store/db"
	runnerstore "github.com/skkap/yad/internal/store"
)

//go:embed migrations/*.sql
var migrations embed.FS

// Store is an open hub database.
type Store struct {
	*db.Queries
	DB *sql.DB
}

// Open opens (creating if needed) the hub database at file and brings its
// schema up to date.
func Open(ctx context.Context, file string) (*Store, error) {
	conn, err := runnerstore.OpenSQLite(ctx, file, migrations)
	if err != nil {
		return nil, fmt.Errorf("hub database %s: %w", file, err)
	}
	return &Store{Queries: db.New(conn), DB: conn}, nil
}

// Close closes the database.
func (s *Store) Close() error { return s.DB.Close() }

// Tx runs fn in a transaction, committing only if it returns nil. The store
// has one connection, so fn must use q and never s.Queries, or it waits on
// itself.
func (s *Store) Tx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	if err := fn(s.Queries.WithTx(tx)); err != nil {
		return errors.Join(err, tx.Rollback())
	}
	return tx.Commit()
}

// Ms is the store's time representation.
func Ms(t time.Time) int64 { return t.UnixMilli() }

// EnqueueRun puts a run in the queue, creating its session when the hub has
// not seen it. It is how tests put work in today, and what `yad hub submit`
// builds on.
func (s *Store) EnqueueRun(ctx context.Context, run v1.Run, now time.Time) error {
	if err := run.Validate(); err != nil {
		return fmt.Errorf("run %q: %w", run.RunID, err)
	}
	if run.Session.Mode == "" {
		run.Session.Mode = v1.SessionPerRun
	}
	spec, err := json.Marshal(run)
	if err != nil {
		return err
	}
	return s.Tx(ctx, func(q *db.Queries) error {
		if err := q.CreateSession(ctx, db.CreateSessionParams{ID: run.Session.ID, Harness: run.Harness, CreatedAt: Ms(now)}); err != nil {
			return err
		}
		sess, err := q.GetSession(ctx, run.Session.ID)
		if err != nil {
			return err
		}
		// A session belongs to one harness: a Codex run cannot resume a Claude
		// conversation.
		if sess.Harness != run.Harness {
			return fmt.Errorf("run %q: session %q is a %s session, not %s — use a new session id", run.RunID, run.Session.ID, sess.Harness, run.Harness)
		}
		return q.CreateRun(ctx, db.CreateRunParams{
			ID: run.RunID, SessionID: run.Session.ID, Harness: run.Harness, Model: run.Model,
			Spec: string(spec), CreatedAt: Ms(now), UpdatedAt: Ms(now),
		})
	})
}
