// Package store is yad hub's durable state: registration tokens, runners,
// sessions, runs, events and results — one SQLite file, separate from any
// runner's state.db.
//
// It is opened exactly as the runner's store is (store.OpenSQLite), with its
// own migrations; the queries live in queries.sql and the Go in db/ is
// generated by sqlc and committed.
package store

import (
	"context"
	"database/sql"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	v1 "github.com/skkap/yad/protocol/v1"

	"github.com/skkap/yad/internal/hub/store/db"
	runnerstore "github.com/skkap/yad/internal/store"
)

//go:embed migrations/*.sql
var migrations embed.FS

// Store is an open hub database.
type Store struct {
	*db.Queries
	DB *sql.DB
}

// Open opens (creating if needed) the hub database at file and brings its
// schema up to date.
func Open(ctx context.Context, file string) (*Store, error) {
	conn, err := runnerstore.OpenSQLite(ctx, file, migrations)
	if err != nil {
		return nil, fmt.Errorf("hub database %s: %w", file, err)
	}
	return &Store{Queries: db.New(conn), DB: conn}, nil
}

// Close closes the database.
func (s *Store) Close() error { return s.DB.Close() }

// Tx runs fn in a transaction, committing only if it returns nil. The store
// has one connection, so fn must use q and never s.Queries, or it waits on
// itself.
func (s *Store) Tx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	if err := fn(s.Queries.WithTx(tx)); err != nil {
		return errors.Join(err, tx.Rollback())
	}
	return tx.Commit()
}

// Ms is the store's time representation.
func Ms(t time.Time) int64 { return t.UnixMilli() }

// Why EnqueueRun refused a run. Each is a different next action for whoever
// submitted it, so the service API answers each with its own status.
var (
	ErrRunExists      = errors.New("the hub already has a run with this id")
	ErrSessionExists  = errors.New("the session already exists")
	ErrNoSession      = errors.New("the hub has no such session")
	ErrSessionHarness = errors.New("the session belongs to another harness")
	ErrSessionClosed  = errors.New("the session is closed")
	// The session a fork names: one the hub does not have, or one no claim
	// has bound to a runner yet, so there is no conversation anywhere to
	// copy (decision 0065). The other refusals of a fork's source are the
	// errors above, naming it.
	ErrNoForkSource = errors.New("the hub has no session to fork by that id")
	ErrForkUnbound  = errors.New("the session to fork is on no runner yet")
)

// forkable checks the session a run opening a fork names, as the runner will
// when it claims the run (decision 0065): the hub's, bound to a runner — the
// one the fork is offered to — of the run's harness, and open.
func forkable(ctx context.Context, q *db.Queries, run v1.Run) error {
	src, err := q.GetSession(ctx, run.Session.ForkFrom)
	switch {
	case errors.Is(err, sql.ErrNoRows):
		return fmt.Errorf("run %q: session %q: %w", run.RunID, run.Session.ForkFrom, ErrNoForkSource)
	case err != nil:
		return err
	case src.ClosedAt.Valid:
		return fmt.Errorf("run %q: session %q to fork was closed (%s): %w", run.RunID, run.Session.ForkFrom, src.CloseReason.String, ErrSessionClosed)
	case src.CloseRequestedAt.Valid:
		return fmt.Errorf("run %q: session %q to fork is closing: %w", run.RunID, run.Session.ForkFrom, ErrSessionClosed)
	case src.Harness != run.Harness:
		return fmt.Errorf("run %q: session %q to fork is a %s session, not %s: %w", run.RunID, run.Session.ForkFrom, src.Harness, run.Harness, ErrSessionHarness)
	case !src.RunnerID.Valid:
		return fmt.Errorf("run %q: session %q: %w", run.RunID, run.Session.ForkFrom, ErrForkUnbound)
	}
	return nil
}

// EnqueueRun puts a run in the queue. A run in a new session creates it; a
// run continuing one needs the hub to have it. The run's own flag says which,
// and it is checked rather than trusted: a "new" run for a session id already
// taken would join a conversation its submitter never meant, and a continuing
// one in no session has nothing to continue. The flag the runner is sent is
// not this one: it is decided at offer, by whether a claim has bound the
// session yet (decision 0047).
func (s *Store) EnqueueRun(ctx context.Context, run v1.Run, now time.Time) error {
	if err := run.Validate(); err != nil {
		return fmt.Errorf("run %q: %w", run.RunID, err)
	}
	if run.Session.Mode == "" {
		run.Session.Mode = v1.SessionPerRun
	}
	spec, err := json.Marshal(run)
	if err != nil {
		return err
	}
	return s.Tx(ctx, func(q *db.Queries) error {
		if _, err := q.GetRun(ctx, run.RunID); err == nil {
			return fmt.Errorf("run %q: %w", run.RunID, ErrRunExists)
		} else if !errors.Is(err, sql.ErrNoRows) {
			return err
		}
		sess, err := q.GetSession(ctx, run.Session.ID)
		switch {
		case err == nil && run.Session.New:
			return fmt.Errorf("run %q: session %q: %w", run.RunID, run.Session.ID, ErrSessionExists)
		case errors.Is(err, sql.ErrNoRows) && !run.Session.New:
			return fmt.Errorf("run %q: session %q: %w", run.RunID, run.Session.ID, ErrNoSession)
		case errors.Is(err, sql.ErrNoRows):
			if run.Session.ForkFrom != "" {
				if err := forkable(ctx, q, run); err != nil {
					return err
				}
			}
			if err := q.CreateSession(ctx, db.CreateSessionParams{
				ID: run.Session.ID, Harness: run.Harness, CreatedAt: Ms(now),
				ForkFrom: sql.NullString{String: run.Session.ForkFrom, Valid: run.Session.ForkFrom != ""},
			}); err != nil {
				return err
			}
		case err != nil:
			return err
		case sess.ClosedAt.Valid:
			return fmt.Errorf("run %q: session %q was closed (%s): %w", run.RunID, run.Session.ID, sess.CloseReason.String, ErrSessionClosed)
		case sess.CloseRequestedAt.Valid:
			return fmt.Errorf("run %q: session %q is closing: %w", run.RunID, run.Session.ID, ErrSessionClosed)
		case sess.Harness != run.Harness:
			// A Codex run cannot resume a Claude conversation.
			return fmt.Errorf("run %q: session %q is a %s session, not %s: %w", run.RunID, run.Session.ID, sess.Harness, run.Harness, ErrSessionHarness)
		}
		return q.CreateRun(ctx, db.CreateRunParams{
			ID: run.RunID, SessionID: run.Session.ID, Harness: run.Harness, Model: run.Model,
			Spec: string(spec), CreatedAt: Ms(now), UpdatedAt: Ms(now),
		})
	})
}
