// Package store is the runner's durable state: sessions, runs, the event spool,
// the result outbox, account limits and slots — one SQLite file per profile.
//
// SQLite rather than files because the spool and outbox must survive a crash in
// order, with (run, seq) unique; that is a transaction and an index, not
// something to hand-build from renames (decision 0016). The queries live in
// queries.sql and the Go in db/ is generated by sqlc and committed.
package store

import (
	"context"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	// modernc is pure Go, so CGO_ENABLED=0 cross-compiles keep working; it
	// registers the "sqlite" driver name.
	_ "modernc.org/sqlite"

	"github.com/skkap/yad/internal/store/db"
)

//go:embed migrations/*.sql
var migrations embed.FS

// Store is an open state database.
type Store struct {
	*db.Queries
	DB *sql.DB
}

// Open opens (creating if needed) the state database at path and brings its
// schema up to date.
func Open(ctx context.Context, file string) (*Store, error) {
	conn, err := OpenSQLite(ctx, file, migrations)
	if err != nil {
		return nil, fmt.Errorf("state database %s: %w", file, err)
	}
	return &Store{Queries: db.New(conn), DB: conn}, nil
}

// OpenSQLite opens a SQLite file the way every YAD database is opened, and
// applies the numbered migrations under migrations/ in fsys. The hub's store
// uses it too, so the two databases cannot drift in how they are opened.
//
// The file is created 0600 before SQLite touches it: both databases hold run
// specs, and the hub's holds credential hashes and grants.
func OpenSQLite(ctx context.Context, file string, fsys fs.FS) (*sql.DB, error) {
	if err := os.MkdirAll(filepath.Dir(file), 0o700); err != nil {
		return nil, err
	}
	f, err := os.OpenFile(file, os.O_RDWR|os.O_CREATE, 0o600)
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", file, err)
	}
	f.Close()

	// WAL lets `yad status` read while the runner writes; busy_timeout turns a
	// brief lock into a wait instead of an error; foreign keys are off by
	// default in SQLite and the schema relies on them.
	q := url.Values{}
	q.Add("_pragma", "journal_mode(WAL)")
	q.Add("_pragma", "busy_timeout(5000)")
	q.Add("_pragma", "foreign_keys(1)")
	q.Add("_pragma", "synchronous(NORMAL)")
	conn, err := sql.Open("sqlite", "file:"+file+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	// One writer at a time is SQLite's model anyway; a single connection makes
	// that explicit and keeps transactions from surprising each other.
	conn.SetMaxOpenConns(1)
	if err := migrate(ctx, conn, fsys); err != nil {
		conn.Close()
		return nil, fmt.Errorf("%w — if this follows a downgrade, run the newer yad", err)
	}
	return conn, nil
}

// ErrNoState is a profile whose runner has never opened its state database.
var ErrNoState = errors.New("no state database yet")

// OpenReadOnly opens the runner's state database for a reader beside the
// daemon — `yad sessions` — without migrating it or creating it: the file is
// the daemon's, and a CLI newer than the daemon must not change the schema
// under it. A database at another schema version than this binary's is
// refused with the way out.
func OpenReadOnly(ctx context.Context, file string) (*Store, error) {
	if _, err := os.Stat(file); errors.Is(err, fs.ErrNotExist) {
		return nil, ErrNoState
	}
	q := url.Values{}
	q.Add("mode", "ro")
	q.Add("_pragma", "busy_timeout(5000)")
	conn, err := sql.Open("sqlite", "file:"+file+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	var current int
	if err := conn.QueryRowContext(ctx, "PRAGMA user_version").Scan(&current); err != nil {
		conn.Close()
		return nil, fmt.Errorf("state database %s: %w", file, err)
	}
	latest, err := latestVersion(migrations)
	if err != nil {
		conn.Close()
		return nil, err
	}
	switch {
	case current < latest:
		conn.Close()
		return nil, fmt.Errorf("state database %s is at schema %d and this yad expects %d — `yad daemon restart` brings it up to date", file, current, latest)
	case current > latest:
		conn.Close()
		return nil, fmt.Errorf("state database %s is at schema %d, newer than this yad knows (%d) — run the newer yad", file, current, latest)
	}
	return &Store{Queries: db.New(conn), DB: conn}, nil
}

// Close closes the database.
func (s *Store) Close() error { return s.DB.Close() }

// Tx runs fn in a transaction, committing only if it returns nil.
func (s *Store) Tx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	if err := fn(s.Queries.WithTx(tx)); err != nil {
		return errors.Join(err, tx.Rollback())
	}
	return tx.Commit()
}

// migrate applies every embedded migration newer than PRAGMA user_version, each
// in its own transaction. A database newer than this binary is refused, never
// guessed at.
func migrate(ctx context.Context, conn *sql.DB, fsys fs.FS) error {
	var current int
	if err := conn.QueryRowContext(ctx, "PRAGMA user_version").Scan(&current); err != nil {
		return err
	}
	files, err := fs.Glob(fsys, "migrations/*.sql")
	if err != nil {
		return err
	}
	sort.Strings(files)
	latest := 0
	for _, name := range files {
		n, err := migrationNumber(name)
		if err != nil {
			return err
		}
		latest = n
		if n <= current {
			continue
		}
		body, err := fs.ReadFile(fsys, name)
		if err != nil {
			return err
		}
		tx, err := conn.BeginTx(ctx, nil)
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, string(body)); err != nil {
			tx.Rollback()
			return fmt.Errorf("migration %s: %w", name, err)
		}
		// PRAGMA takes no bound parameters; n is an int we parsed ourselves.
		if _, err := tx.ExecContext(ctx, fmt.Sprintf("PRAGMA user_version = %d", n)); err != nil {
			tx.Rollback()
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
	}
	if current > latest {
		return fmt.Errorf("schema version %d is newer than this binary knows (%d)", current, latest)
	}
	return nil
}

func migrationNumber(name string) (int, error) {
	n, err := strconv.Atoi(strings.SplitN(path.Base(name), "_", 2)[0])
	if err != nil {
		return 0, fmt.Errorf("migration %s has no numeric prefix", name)
	}
	return n, nil
}

// latestVersion is the schema version the embedded migrations end at.
func latestVersion(fsys fs.FS) (int, error) {
	files, err := fs.Glob(fsys, "migrations/*.sql")
	if err != nil {
		return 0, err
	}
	latest := 0
	for _, name := range files {
		n, err := migrationNumber(name)
		if err != nil {
			return 0, err
		}
		latest = max(latest, n)
	}
	return latest, nil
}
