// Package store is the runner's durable state: sessions, runs, the event spool,
// the result outbox, account limits and slots — one SQLite file per profile.
//
// SQLite rather than files because the spool and outbox must survive a crash in
// order, with (run, seq) unique; that is a transaction and an index, not
// something to hand-build from renames (decision 0016). The queries live in
// queries.sql and the Go in db/ is generated by sqlc and committed.
package store

import (
	"context"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	// modernc is pure Go, so CGO_ENABLED=0 cross-compiles keep working; it
	// registers the "sqlite" driver name.
	_ "modernc.org/sqlite"

	"github.com/skkap/yad/internal/store/db"
)

//go:embed migrations/*.sql
var migrations embed.FS

// Store is an open state database.
type Store struct {
	*db.Queries
	DB *sql.DB
}

// Open opens (creating if needed) the state database at path and brings its
// schema up to date. The file is created 0600 before SQLite touches it: it holds
// run specs and harness output, which contain whatever the repositories do.
func Open(ctx context.Context, file string) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(file), 0o700); err != nil {
		return nil, err
	}
	f, err := os.OpenFile(file, os.O_RDWR|os.O_CREATE, 0o600)
	if err != nil {
		return nil, fmt.Errorf("open state database %s: %w", file, err)
	}
	f.Close()

	// WAL lets `yad status` read while the runner writes; busy_timeout turns a
	// brief lock into a wait instead of an error; foreign keys are off by
	// default in SQLite and the schema relies on them.
	q := url.Values{}
	q.Add("_pragma", "journal_mode(WAL)")
	q.Add("_pragma", "busy_timeout(5000)")
	q.Add("_pragma", "foreign_keys(1)")
	q.Add("_pragma", "synchronous(NORMAL)")
	conn, err := sql.Open("sqlite", "file:"+file+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	// One writer at a time is SQLite's model anyway; a single connection makes
	// that explicit and keeps transactions from surprising each other.
	conn.SetMaxOpenConns(1)
	if err := migrate(ctx, conn); err != nil {
		conn.Close()
		return nil, fmt.Errorf("state database %s: %w — if this follows a downgrade, run the newer yad", file, err)
	}
	return &Store{Queries: db.New(conn), DB: conn}, nil
}

// Close closes the database.
func (s *Store) Close() error { return s.DB.Close() }

// Tx runs fn in a transaction, committing only if it returns nil.
func (s *Store) Tx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	if err := fn(s.Queries.WithTx(tx)); err != nil {
		return errors.Join(err, tx.Rollback())
	}
	return tx.Commit()
}

// migrate applies every embedded migration newer than PRAGMA user_version, each
// in its own transaction. A database newer than this binary is refused, never
// guessed at.
func migrate(ctx context.Context, conn *sql.DB) error {
	var current int
	if err := conn.QueryRowContext(ctx, "PRAGMA user_version").Scan(&current); err != nil {
		return err
	}
	files, err := fs.Glob(migrations, "migrations/*.sql")
	if err != nil {
		return err
	}
	sort.Strings(files)
	latest := 0
	for _, name := range files {
		n, err := strconv.Atoi(strings.SplitN(path.Base(name), "_", 2)[0])
		if err != nil {
			return fmt.Errorf("migration %s has no numeric prefix", name)
		}
		latest = n
		if n <= current {
			continue
		}
		body, err := migrations.ReadFile(name)
		if err != nil {
			return err
		}
		tx, err := conn.BeginTx(ctx, nil)
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, string(body)); err != nil {
			tx.Rollback()
			return fmt.Errorf("migration %s: %w", name, err)
		}
		// PRAGMA takes no bound parameters; n is an int we parsed ourselves.
		if _, err := tx.ExecContext(ctx, fmt.Sprintf("PRAGMA user_version = %d", n)); err != nil {
			tx.Rollback()
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
	}
	if current > latest {
		return fmt.Errorf("schema version %d is newer than this binary knows (%d)", current, latest)
	}
	return nil
}
