// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Account struct {
	Harness      string
	Label        string
	LimitedUntil sql.NullInt64
}

type Event struct {
	RunID string
	Seq   int64
	Body  string
	Acked int64
}

type Outbox struct {
	RunID         string
	Connection    string
	Body          string
	Attempts      int64
	NextAttemptAt int64
	LastError     sql.NullString
}

type Run struct {
	ID         string
	SessionID  string
	Connection string
	Harness    string
	Model      string
	State      string
	Spec       string
	Account    sql.NullString
	ResumesAt  sql.NullInt64
	Reason     sql.NullString
	CreatedAt  int64
	UpdatedAt  int64
}

type Session struct {
	ID         string
	Connection string
	Harness    string
	NativeID   sql.NullString
	Account    sql.NullString
	Workdir    string
	State      string
	CreatedAt  int64
	LastUsedAt int64
}

type Slot struct {
	Repo      string
	Slot      int64
	SessionID string
}
