// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const ackEvents = `-- name: AckEvents :exec
UPDATE events SET acked = 1 WHERE run_id = ? AND seq <= ?
`

type AckEventsParams struct {
	RunID string
	Seq   int64
}

func (q *Queries) AckEvents(ctx context.Context, arg AckEventsParams) error {
	_, err := q.db.ExecContext(ctx, ackEvents, arg.RunID, arg.Seq)
	return err
}

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (run_id, seq, body) VALUES (?, ?, ?)
`

type AppendEventParams struct {
	RunID string
	Seq   int64
	Body  string
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent, arg.RunID, arg.Seq, arg.Body)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, session_id, connection, harness, model, state, spec, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'claimed', ?, ?, ?)
`

type CreateRunParams struct {
	ID         string
	SessionID  string
	Connection string
	Harness    string
	Model      string
	Spec       string
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.SessionID,
		arg.Connection,
		arg.Harness,
		arg.Model,
		arg.Spec,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, connection, harness, account, workdir, created_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID         string
	Connection string
	Harness    string
	Account    sql.NullString
	Workdir    string
	CreatedAt  int64
	LastUsedAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Connection,
		arg.Harness,
		arg.Account,
		arg.Workdir,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteOutbox = `-- name: DeleteOutbox :exec
DELETE FROM outbox WHERE run_id = ?
`

func (q *Queries) DeleteOutbox(ctx context.Context, runID string) error {
	_, err := q.db.ExecContext(ctx, deleteOutbox, runID)
	return err
}

const dueOutbox = `-- name: DueOutbox :many
SELECT run_id, connection, body, attempts, next_attempt_at, last_error FROM outbox WHERE connection = ? AND next_attempt_at <= ? ORDER BY next_attempt_at
`

type DueOutboxParams struct {
	Connection    string
	NextAttemptAt int64
}

func (q *Queries) DueOutbox(ctx context.Context, arg DueOutboxParams) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, dueOutbox, arg.Connection, arg.NextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.RunID,
			&i.Connection,
			&i.Body,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const freeSlots = `-- name: FreeSlots :exec
DELETE FROM slots WHERE session_id = ?
`

func (q *Queries) FreeSlots(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, freeSlots, sessionID)
	return err
}

const getRun = `-- name: GetRun :one
SELECT id, session_id, connection, harness, model, state, spec, account, resumes_at, reason, created_at, updated_at FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Connection,
		&i.Harness,
		&i.Model,
		&i.State,
		&i.Spec,
		&i.Account,
		&i.ResumesAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, connection, harness, native_id, account, workdir, state, created_at, last_used_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Connection,
		&i.Harness,
		&i.NativeID,
		&i.Account,
		&i.Workdir,
		&i.State,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT harness, label, limited_until FROM accounts WHERE harness = ? ORDER BY label
`

func (q *Queries) ListAccounts(ctx context.Context, harness string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, harness)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.Harness, &i.Label, &i.LimitedUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeldRuns = `-- name: ListHeldRuns :many
SELECT id, session_id, connection, harness, model, state, spec, account, resumes_at, reason, created_at, updated_at FROM runs
WHERE connection = ? AND state IN ('claimed', 'preparing', 'running', 'waiting')
ORDER BY created_at
`

func (q *Queries) ListHeldRuns(ctx context.Context, connection string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listHeldRuns, connection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Connection,
			&i.Harness,
			&i.Model,
			&i.State,
			&i.Spec,
			&i.Account,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdleSessions = `-- name: ListIdleSessions :many
SELECT id, connection, harness, native_id, account, workdir, state, created_at, last_used_at FROM sessions WHERE state = 'open' AND last_used_at < ? ORDER BY last_used_at
`

func (q *Queries) ListIdleSessions(ctx context.Context, lastUsedAt int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listIdleSessions, lastUsedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Connection,
			&i.Harness,
			&i.NativeID,
			&i.Account,
			&i.Workdir,
			&i.State,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxDepth = `-- name: OutboxDepth :one
SELECT count(*) FROM outbox
`

func (q *Queries) OutboxDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, outboxDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const putOutbox = `-- name: PutOutbox :exec
INSERT INTO outbox (run_id, connection, body, next_attempt_at) VALUES (?, ?, ?, ?)
ON CONFLICT (run_id) DO NOTHING
`

type PutOutboxParams struct {
	RunID         string
	Connection    string
	Body          string
	NextAttemptAt int64
}

func (q *Queries) PutOutbox(ctx context.Context, arg PutOutboxParams) error {
	_, err := q.db.ExecContext(ctx, putOutbox,
		arg.RunID,
		arg.Connection,
		arg.Body,
		arg.NextAttemptAt,
	)
	return err
}

const retryOutbox = `-- name: RetryOutbox :exec
UPDATE outbox SET attempts = attempts + 1, next_attempt_at = ?, last_error = ? WHERE run_id = ?
`

type RetryOutboxParams struct {
	NextAttemptAt int64
	LastError     sql.NullString
	RunID         string
}

func (q *Queries) RetryOutbox(ctx context.Context, arg RetryOutboxParams) error {
	_, err := q.db.ExecContext(ctx, retryOutbox, arg.NextAttemptAt, arg.LastError, arg.RunID)
	return err
}

const setAccountLimit = `-- name: SetAccountLimit :exec
INSERT INTO accounts (harness, label, limited_until) VALUES (?, ?, ?)
ON CONFLICT (harness, label) DO UPDATE SET limited_until = excluded.limited_until
`

type SetAccountLimitParams struct {
	Harness      string
	Label        string
	LimitedUntil sql.NullInt64
}

func (q *Queries) SetAccountLimit(ctx context.Context, arg SetAccountLimitParams) error {
	_, err := q.db.ExecContext(ctx, setAccountLimit, arg.Harness, arg.Label, arg.LimitedUntil)
	return err
}

const setRunAccount = `-- name: SetRunAccount :exec
UPDATE runs SET account = ?, updated_at = ? WHERE id = ?
`

type SetRunAccountParams struct {
	Account   sql.NullString
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetRunAccount(ctx context.Context, arg SetRunAccountParams) error {
	_, err := q.db.ExecContext(ctx, setRunAccount, arg.Account, arg.UpdatedAt, arg.ID)
	return err
}

const setRunState = `-- name: SetRunState :exec
UPDATE runs SET state = ?, resumes_at = ?, reason = ?, updated_at = ? WHERE id = ?
`

type SetRunStateParams struct {
	State     string
	ResumesAt sql.NullInt64
	Reason    sql.NullString
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetRunState(ctx context.Context, arg SetRunStateParams) error {
	_, err := q.db.ExecContext(ctx, setRunState,
		arg.State,
		arg.ResumesAt,
		arg.Reason,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setSessionNativeID = `-- name: SetSessionNativeID :exec
UPDATE sessions SET native_id = ?, last_used_at = ? WHERE id = ?
`

type SetSessionNativeIDParams struct {
	NativeID   sql.NullString
	LastUsedAt int64
	ID         string
}

func (q *Queries) SetSessionNativeID(ctx context.Context, arg SetSessionNativeIDParams) error {
	_, err := q.db.ExecContext(ctx, setSessionNativeID, arg.NativeID, arg.LastUsedAt, arg.ID)
	return err
}

const setSessionState = `-- name: SetSessionState :exec
UPDATE sessions SET state = ?, last_used_at = ? WHERE id = ?
`

type SetSessionStateParams struct {
	State      string
	LastUsedAt int64
	ID         string
}

func (q *Queries) SetSessionState(ctx context.Context, arg SetSessionStateParams) error {
	_, err := q.db.ExecContext(ctx, setSessionState, arg.State, arg.LastUsedAt, arg.ID)
	return err
}

const slotsInUse = `-- name: SlotsInUse :many
SELECT slot FROM slots WHERE repo = ? ORDER BY slot
`

func (q *Queries) SlotsInUse(ctx context.Context, repo string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, slotsInUse, repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var slot int64
		if err := rows.Scan(&slot); err != nil {
			return nil, err
		}
		items = append(items, slot)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spoolDepth = `-- name: SpoolDepth :one
SELECT count(*) FROM events WHERE acked = 0
`

func (q *Queries) SpoolDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, spoolDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const takeSlot = `-- name: TakeSlot :exec
INSERT INTO slots (repo, slot, session_id) VALUES (?, ?, ?)
`

type TakeSlotParams struct {
	Repo      string
	Slot      int64
	SessionID string
}

func (q *Queries) TakeSlot(ctx context.Context, arg TakeSlotParams) error {
	_, err := q.db.ExecContext(ctx, takeSlot, arg.Repo, arg.Slot, arg.SessionID)
	return err
}

const unackedEvents = `-- name: UnackedEvents :many
SELECT seq, body FROM events WHERE run_id = ? AND acked = 0 ORDER BY seq LIMIT ?
`

type UnackedEventsParams struct {
	RunID string
	Limit int64
}

type UnackedEventsRow struct {
	Seq  int64
	Body string
}

func (q *Queries) UnackedEvents(ctx context.Context, arg UnackedEventsParams) ([]UnackedEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, unackedEvents, arg.RunID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnackedEventsRow{}
	for rows.Next() {
		var i UnackedEventsRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
