// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const ackEvents = `-- name: AckEvents :exec
UPDATE events SET acked = (seq <= ?1)
WHERE connection = ?2 AND run_id = ?3
`

type AckEventsParams struct {
	AckedThrough int64
	Connection   string
	RunID        string
}

// The hub's acked_through is authoritative both ways: everything after it is
// unacknowledged again, so a hub that lost events gets them resent.
func (q *Queries) AckEvents(ctx context.Context, arg AckEventsParams) error {
	_, err := q.db.ExecContext(ctx, ackEvents, arg.AckedThrough, arg.Connection, arg.RunID)
	return err
}

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (connection, run_id, seq, body) VALUES (?, ?, ?, ?)
`

type AppendEventParams struct {
	Connection string
	RunID      string
	Seq        int64
	Body       string
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent,
		arg.Connection,
		arg.RunID,
		arg.Seq,
		arg.Body,
	)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (connection, id, session_id, harness, model, state, spec, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'claimed', ?, ?, ?)
`

type CreateRunParams struct {
	Connection string
	ID         string
	SessionID  string
	Harness    string
	Model      string
	Spec       string
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.Connection,
		arg.ID,
		arg.SessionID,
		arg.Harness,
		arg.Model,
		arg.Spec,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (connection, id, harness, account, workdir, created_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	Connection string
	ID         string
	Harness    string
	Account    sql.NullString
	Workdir    string
	CreatedAt  int64
	LastUsedAt int64
}

// Every hub-issued id (session, run) is addressed together with its
// connection; see the note at the top of migrations/0001_init.sql.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.Connection,
		arg.ID,
		arg.Harness,
		arg.Account,
		arg.Workdir,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteEmptySession = `-- name: DeleteEmptySession :exec
DELETE FROM sessions WHERE sessions.connection = ?1 AND sessions.id = ?2
  AND NOT EXISTS (SELECT 1 FROM runs r WHERE r.connection = sessions.connection AND r.session_id = sessions.id)
`

type DeleteEmptySessionParams struct {
	Connection string
	ID         string
}

func (q *Queries) DeleteEmptySession(ctx context.Context, arg DeleteEmptySessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmptySession, arg.Connection, arg.ID)
	return err
}

const deleteOutbox = `-- name: DeleteOutbox :exec
DELETE FROM outbox WHERE connection = ? AND run_id = ?
`

type DeleteOutboxParams struct {
	Connection string
	RunID      string
}

func (q *Queries) DeleteOutbox(ctx context.Context, arg DeleteOutboxParams) error {
	_, err := q.db.ExecContext(ctx, deleteOutbox, arg.Connection, arg.RunID)
	return err
}

const deleteUnstartedRun = `-- name: DeleteUnstartedRun :exec
DELETE FROM runs WHERE runs.connection = ?1 AND runs.id = ?2
  AND NOT EXISTS (SELECT 1 FROM events e WHERE e.connection = runs.connection AND e.run_id = runs.id)
  AND NOT EXISTS (SELECT 1 FROM outbox o WHERE o.connection = runs.connection AND o.run_id = runs.id)
`

type DeleteUnstartedRunParams struct {
	Connection string
	ID         string
}

// A claim the hub withdrew before it started left nothing worth keeping, and
// the hub may offer the same run again; the row must not be in the way.
func (q *Queries) DeleteUnstartedRun(ctx context.Context, arg DeleteUnstartedRunParams) error {
	_, err := q.db.ExecContext(ctx, deleteUnstartedRun, arg.Connection, arg.ID)
	return err
}

const dropEvents = `-- name: DropEvents :exec
UPDATE events SET acked = 1 WHERE connection = ? AND run_id = ?
`

type DropEventsParams struct {
	Connection string
	RunID      string
}

func (q *Queries) DropEvents(ctx context.Context, arg DropEventsParams) error {
	_, err := q.db.ExecContext(ctx, dropEvents, arg.Connection, arg.RunID)
	return err
}

const dueOutbox = `-- name: DueOutbox :many
SELECT connection, run_id, body, attempts, next_attempt_at, last_error FROM outbox WHERE connection = ? AND next_attempt_at <= ? ORDER BY next_attempt_at
`

type DueOutboxParams struct {
	Connection    string
	NextAttemptAt int64
}

func (q *Queries) DueOutbox(ctx context.Context, arg DueOutboxParams) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, dueOutbox, arg.Connection, arg.NextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.Connection,
			&i.RunID,
			&i.Body,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const freeSlots = `-- name: FreeSlots :exec
DELETE FROM slots WHERE connection = ? AND session_id = ?
`

type FreeSlotsParams struct {
	Connection string
	SessionID  string
}

func (q *Queries) FreeSlots(ctx context.Context, arg FreeSlotsParams) error {
	_, err := q.db.ExecContext(ctx, freeSlots, arg.Connection, arg.SessionID)
	return err
}

const getRun = `-- name: GetRun :one
SELECT connection, id, session_id, harness, model, state, spec, account, resumes_at, reason, created_at, updated_at FROM runs WHERE connection = ? AND id = ?
`

type GetRunParams struct {
	Connection string
	ID         string
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, arg.Connection, arg.ID)
	var i Run
	err := row.Scan(
		&i.Connection,
		&i.ID,
		&i.SessionID,
		&i.Harness,
		&i.Model,
		&i.State,
		&i.Spec,
		&i.Account,
		&i.ResumesAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT connection, id, harness, native_id, account, workdir, state, created_at, last_used_at FROM sessions WHERE connection = ? AND id = ?
`

type GetSessionParams struct {
	Connection string
	ID         string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.Connection, arg.ID)
	var i Session
	err := row.Scan(
		&i.Connection,
		&i.ID,
		&i.Harness,
		&i.NativeID,
		&i.Account,
		&i.Workdir,
		&i.State,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const hasUnackedEvents = `-- name: HasUnackedEvents :one
SELECT EXISTS (SELECT 1 FROM events WHERE connection = ? AND run_id = ? AND acked = 0)
`

type HasUnackedEventsParams struct {
	Connection string
	RunID      string
}

func (q *Queries) HasUnackedEvents(ctx context.Context, arg HasUnackedEventsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUnackedEvents, arg.Connection, arg.RunID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lastEventSeq = `-- name: LastEventSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER) FROM events WHERE connection = ? AND run_id = ?
`

type LastEventSeqParams struct {
	Connection string
	RunID      string
}

// The last event a run spooled, acknowledged or not: a result's last_seq.
func (q *Queries) LastEventSeq(ctx context.Context, arg LastEventSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastEventSeq, arg.Connection, arg.RunID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT harness, label, limited_until FROM accounts WHERE harness = ? ORDER BY label
`

func (q *Queries) ListAccounts(ctx context.Context, harness string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, harness)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.Harness, &i.Label, &i.LimitedUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeldRuns = `-- name: ListHeldRuns :many
SELECT connection, id, session_id, harness, model, state, spec, account, resumes_at, reason, created_at, updated_at FROM runs
WHERE connection = ? AND state IN ('claimed', 'preparing', 'running', 'waiting')
ORDER BY created_at
`

func (q *Queries) ListHeldRuns(ctx context.Context, connection string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listHeldRuns, connection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.State,
			&i.Spec,
			&i.Account,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdleSessions = `-- name: ListIdleSessions :many
SELECT connection, id, harness, native_id, account, workdir, state, created_at, last_used_at FROM sessions WHERE state = 'open' AND last_used_at < ? ORDER BY last_used_at
`

func (q *Queries) ListIdleSessions(ctx context.Context, lastUsedAt int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listIdleSessions, lastUsedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.Harness,
			&i.NativeID,
			&i.Account,
			&i.Workdir,
			&i.State,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportingRuns = `-- name: ListReportingRuns :many
SELECT r.connection, r.id, r.session_id, r.harness, r.model, r.state, r.spec, r.account, r.resumes_at, r.reason, r.created_at, r.updated_at FROM runs r JOIN outbox o ON o.connection = r.connection AND o.run_id = r.id
WHERE r.connection = ? ORDER BY r.created_at
`

// A finished run whose result the hub has not acknowledged is still this
// runner's: listing it keeps its lease alive, so a hub outage longer than a
// lease does not turn a finished run into a lost one.
func (q *Queries) ListReportingRuns(ctx context.Context, connection string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listReportingRuns, connection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.State,
			&i.Spec,
			&i.Account,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxDepth = `-- name: OutboxDepth :one
SELECT count(*) FROM outbox
`

func (q *Queries) OutboxDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, outboxDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const putOutbox = `-- name: PutOutbox :exec
INSERT INTO outbox (connection, run_id, body, next_attempt_at) VALUES (?, ?, ?, ?)
ON CONFLICT (connection, run_id) DO NOTHING
`

type PutOutboxParams struct {
	Connection    string
	RunID         string
	Body          string
	NextAttemptAt int64
}

func (q *Queries) PutOutbox(ctx context.Context, arg PutOutboxParams) error {
	_, err := q.db.ExecContext(ctx, putOutbox,
		arg.Connection,
		arg.RunID,
		arg.Body,
		arg.NextAttemptAt,
	)
	return err
}

const retryOutbox = `-- name: RetryOutbox :exec
UPDATE outbox SET attempts = attempts + 1, next_attempt_at = ?, last_error = ? WHERE connection = ? AND run_id = ?
`

type RetryOutboxParams struct {
	NextAttemptAt int64
	LastError     sql.NullString
	Connection    string
	RunID         string
}

func (q *Queries) RetryOutbox(ctx context.Context, arg RetryOutboxParams) error {
	_, err := q.db.ExecContext(ctx, retryOutbox,
		arg.NextAttemptAt,
		arg.LastError,
		arg.Connection,
		arg.RunID,
	)
	return err
}

const runsWithUnackedEvents = `-- name: RunsWithUnackedEvents :many
SELECT DISTINCT run_id FROM events WHERE connection = ? AND acked = 0 ORDER BY run_id
`

func (q *Queries) RunsWithUnackedEvents(ctx context.Context, connection string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, runsWithUnackedEvents, connection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var run_id string
		if err := rows.Scan(&run_id); err != nil {
			return nil, err
		}
		items = append(items, run_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountLimit = `-- name: SetAccountLimit :exec
INSERT INTO accounts (harness, label, limited_until) VALUES (?, ?, ?)
ON CONFLICT (harness, label) DO UPDATE SET limited_until = excluded.limited_until
`

type SetAccountLimitParams struct {
	Harness      string
	Label        string
	LimitedUntil sql.NullInt64
}

func (q *Queries) SetAccountLimit(ctx context.Context, arg SetAccountLimitParams) error {
	_, err := q.db.ExecContext(ctx, setAccountLimit, arg.Harness, arg.Label, arg.LimitedUntil)
	return err
}

const setRunAccount = `-- name: SetRunAccount :exec
UPDATE runs SET account = ?, updated_at = ? WHERE connection = ? AND id = ?
`

type SetRunAccountParams struct {
	Account    sql.NullString
	UpdatedAt  int64
	Connection string
	ID         string
}

func (q *Queries) SetRunAccount(ctx context.Context, arg SetRunAccountParams) error {
	_, err := q.db.ExecContext(ctx, setRunAccount,
		arg.Account,
		arg.UpdatedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const setRunState = `-- name: SetRunState :exec
UPDATE runs SET state = ?, resumes_at = ?, reason = ?, updated_at = ? WHERE connection = ? AND id = ?
`

type SetRunStateParams struct {
	State      string
	ResumesAt  sql.NullInt64
	Reason     sql.NullString
	UpdatedAt  int64
	Connection string
	ID         string
}

func (q *Queries) SetRunState(ctx context.Context, arg SetRunStateParams) error {
	_, err := q.db.ExecContext(ctx, setRunState,
		arg.State,
		arg.ResumesAt,
		arg.Reason,
		arg.UpdatedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const setSessionNativeID = `-- name: SetSessionNativeID :exec
UPDATE sessions SET native_id = ?, last_used_at = ? WHERE connection = ? AND id = ?
`

type SetSessionNativeIDParams struct {
	NativeID   sql.NullString
	LastUsedAt int64
	Connection string
	ID         string
}

func (q *Queries) SetSessionNativeID(ctx context.Context, arg SetSessionNativeIDParams) error {
	_, err := q.db.ExecContext(ctx, setSessionNativeID,
		arg.NativeID,
		arg.LastUsedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const setSessionState = `-- name: SetSessionState :exec
UPDATE sessions SET state = ?, last_used_at = ? WHERE connection = ? AND id = ?
`

type SetSessionStateParams struct {
	State      string
	LastUsedAt int64
	Connection string
	ID         string
}

func (q *Queries) SetSessionState(ctx context.Context, arg SetSessionStateParams) error {
	_, err := q.db.ExecContext(ctx, setSessionState,
		arg.State,
		arg.LastUsedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const setSessionWorkdir = `-- name: SetSessionWorkdir :exec
UPDATE sessions SET workdir = ?, last_used_at = ? WHERE connection = ? AND id = ?
`

type SetSessionWorkdirParams struct {
	Workdir    string
	LastUsedAt int64
	Connection string
	ID         string
}

func (q *Queries) SetSessionWorkdir(ctx context.Context, arg SetSessionWorkdirParams) error {
	_, err := q.db.ExecContext(ctx, setSessionWorkdir,
		arg.Workdir,
		arg.LastUsedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const slotsInUse = `-- name: SlotsInUse :many
SELECT slot FROM slots WHERE repo = ? ORDER BY slot
`

func (q *Queries) SlotsInUse(ctx context.Context, repo string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, slotsInUse, repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var slot int64
		if err := rows.Scan(&slot); err != nil {
			return nil, err
		}
		items = append(items, slot)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spoolDepth = `-- name: SpoolDepth :one
SELECT count(*) FROM events WHERE acked = 0
`

func (q *Queries) SpoolDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, spoolDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const takeSlot = `-- name: TakeSlot :exec
INSERT INTO slots (repo, slot, connection, session_id) VALUES (?, ?, ?, ?)
`

type TakeSlotParams struct {
	Repo       string
	Slot       int64
	Connection string
	SessionID  string
}

func (q *Queries) TakeSlot(ctx context.Context, arg TakeSlotParams) error {
	_, err := q.db.ExecContext(ctx, takeSlot,
		arg.Repo,
		arg.Slot,
		arg.Connection,
		arg.SessionID,
	)
	return err
}

const unackedEvents = `-- name: UnackedEvents :many
SELECT seq, body FROM events WHERE connection = ? AND run_id = ? AND acked = 0 ORDER BY seq LIMIT ?
`

type UnackedEventsParams struct {
	Connection string
	RunID      string
	Limit      int64
}

type UnackedEventsRow struct {
	Seq  int64
	Body string
}

func (q *Queries) UnackedEvents(ctx context.Context, arg UnackedEventsParams) ([]UnackedEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, unackedEvents, arg.Connection, arg.RunID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnackedEventsRow{}
	for rows.Next() {
		var i UnackedEventsRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
