// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const ackEvents = `-- name: AckEvents :exec
UPDATE events SET acked = (seq <= ?1)
WHERE connection = ?2 AND run_id = ?3
`

type AckEventsParams struct {
	AckedThrough int64
	Connection   string
	RunID        string
}

// The hub's acked_through is authoritative both ways: everything after it is
// unacknowledged again, so a hub that lost events gets them resent.
func (q *Queries) AckEvents(ctx context.Context, arg AckEventsParams) error {
	_, err := q.db.ExecContext(ctx, ackEvents, arg.AckedThrough, arg.Connection, arg.RunID)
	return err
}

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (connection, run_id, seq, body) VALUES (?, ?, ?, ?)
`

type AppendEventParams struct {
	Connection string
	RunID      string
	Seq        int64
	Body       string
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent,
		arg.Connection,
		arg.RunID,
		arg.Seq,
		arg.Body,
	)
	return err
}

const closeRequestedEmptySession = `-- name: CloseRequestedEmptySession :execrows
UPDATE sessions SET state = CASE WHEN close_reason IN ('expired', 'disk_pressure') THEN 'expired' ELSE 'closed' END,
  closed_at = ?1, close_requested_at = NULL
WHERE sessions.connection = ?2 AND sessions.id = ?3 AND sessions.state = 'open'
  AND sessions.close_requested_at IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM runs r WHERE r.connection = sessions.connection AND r.session_id = sessions.id
    AND r.state IN ('claimed', 'preparing', 'running', 'waiting'))
`

type CloseRequestedEmptySessionParams struct {
	Now        sql.NullInt64
	Connection string
	ID         string
}

// A close that waited on a claim which was then withdrawn: nothing is held in
// the session any more, so it closes in the withdrawal's own transaction, with
// the reason first asked for, and the next sync reports it. The state follows
// the reason as the collector's close does.
func (q *Queries) CloseRequestedEmptySession(ctx context.Context, arg CloseRequestedEmptySessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeRequestedEmptySession, arg.Now, arg.Connection, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeSession = `-- name: CloseSession :execrows
UPDATE sessions SET state = ?1, close_reason = COALESCE(close_reason, ?2), closed_at = ?3,
  close_requested_at = NULL
WHERE sessions.connection = ?4 AND sessions.id = ?5 AND sessions.state = 'open'
  AND NOT EXISTS (SELECT 1 FROM runs r WHERE r.connection = sessions.connection AND r.session_id = sessions.id
    AND r.state IN ('claimed', 'preparing', 'running', 'waiting'))
`

type CloseSessionParams struct {
	State      string
	Reason     sql.NullString
	Now        sql.NullInt64
	Connection string
	ID         string
}

// Workdir collection (decision 0035). A run held (claimed, preparing,
// running, or waiting on a usage limit or its start time) keeps its session
// open whatever else is true: its workdir is in use. The close is one
// statement, so a claim cannot slip a run into the session between the check
// and the write; it answers 0 rows when a run is held or the session is not
// open. A reason already asked for while a run was held stands.
func (q *Queries) CloseSession(ctx context.Context, arg CloseSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeSession,
		arg.State,
		arg.Reason,
		arg.Now,
		arg.Connection,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countOpenSessions = `-- name: CountOpenSessions :one
SELECT count(*) FROM sessions WHERE state = 'open'
`

func (q *Queries) CountOpenSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (connection, id, session_id, harness, model, state, spec, had_grants, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'claimed', ?, ?, ?, ?)
`

type CreateRunParams struct {
	Connection string
	ID         string
	SessionID  string
	Harness    string
	Model      string
	Spec       string
	HadGrants  int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.Connection,
		arg.ID,
		arg.SessionID,
		arg.Harness,
		arg.Model,
		arg.Spec,
		arg.HadGrants,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec


INSERT INTO sessions (connection, id, harness, account, workdir, created_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	Connection string
	ID         string
	Harness    string
	Account    sql.NullString
	Workdir    string
	CreatedAt  int64
	LastUsedAt int64
}

// Every hub-issued id (session, run) is addressed together with its
// connection; see the note at the top of migrations/0001_init.sql.
// ASCII only in this file, comments included. sqlc 1.31.1 rewrites each query
// using byte offsets it computed over runes, so one multi-byte character
// anywhere above a query truncates that query's text and every later one:
// `SELECT *` arrives at its parser as `SELECharness` and generation fails
// naming queries nobody touched. The repo's prose uses an em dash; here it
// costs an afternoon. (Confirmed by adding one and removing it again, DEV-27.)
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.Connection,
		arg.ID,
		arg.Harness,
		arg.Account,
		arg.Workdir,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE harness = ? AND label = ?
`

type DeleteAccountParams struct {
	Harness string
	Label   string
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, arg.Harness, arg.Label)
	return err
}

const deleteAccountWindows = `-- name: DeleteAccountWindows :exec
DELETE FROM account_windows WHERE harness = ? AND label = ?
`

type DeleteAccountWindowsParams struct {
	Harness string
	Label   string
}

// An account's windows go with the account. Left behind, they would be
// reported against a label the owner re-added for a different subscription.
func (q *Queries) DeleteAccountWindows(ctx context.Context, arg DeleteAccountWindowsParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccountWindows, arg.Harness, arg.Label)
	return err
}

const deleteEmptySession = `-- name: DeleteEmptySession :exec
DELETE FROM sessions WHERE sessions.connection = ?1 AND sessions.id = ?2
  AND sessions.state = 'open' AND sessions.close_requested_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM runs r WHERE r.connection = sessions.connection AND r.session_id = sessions.id)
`

type DeleteEmptySessionParams struct {
	Connection string
	ID         string
}

// A session a withdrawn claim opened goes with it, so the hub can offer the
// run again. Not one with a close asked for: that close was answered
// "closing" and must still happen and be reported (decision 0035), so
// CloseRequestedEmptySession closes it instead. Deleting it would lose the
// close and let the re-offer open the session afresh.
func (q *Queries) DeleteEmptySession(ctx context.Context, arg DeleteEmptySessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmptySession, arg.Connection, arg.ID)
	return err
}

const deleteOutbox = `-- name: DeleteOutbox :exec
DELETE FROM outbox WHERE connection = ? AND run_id = ?
`

type DeleteOutboxParams struct {
	Connection string
	RunID      string
}

func (q *Queries) DeleteOutbox(ctx context.Context, arg DeleteOutboxParams) error {
	_, err := q.db.ExecContext(ctx, deleteOutbox, arg.Connection, arg.RunID)
	return err
}

const deleteUnstartedRun = `-- name: DeleteUnstartedRun :exec
DELETE FROM runs WHERE runs.connection = ?1 AND runs.id = ?2
  AND NOT EXISTS (SELECT 1 FROM events e WHERE e.connection = runs.connection AND e.run_id = runs.id)
  AND NOT EXISTS (SELECT 1 FROM outbox o WHERE o.connection = runs.connection AND o.run_id = runs.id)
`

type DeleteUnstartedRunParams struct {
	Connection string
	ID         string
}

// A claim the hub withdrew before it started left nothing worth keeping, and
// the hub may offer the same run again; the row must not be in the way.
func (q *Queries) DeleteUnstartedRun(ctx context.Context, arg DeleteUnstartedRunParams) error {
	_, err := q.db.ExecContext(ctx, deleteUnstartedRun, arg.Connection, arg.ID)
	return err
}

const dropEvents = `-- name: DropEvents :exec
UPDATE events SET acked = 1 WHERE connection = ? AND run_id = ?
`

type DropEventsParams struct {
	Connection string
	RunID      string
}

func (q *Queries) DropEvents(ctx context.Context, arg DropEventsParams) error {
	_, err := q.db.ExecContext(ctx, dropEvents, arg.Connection, arg.RunID)
	return err
}

const dueOutbox = `-- name: DueOutbox :many
SELECT connection, run_id, body, attempts, next_attempt_at, last_error FROM outbox WHERE connection = ? AND next_attempt_at <= ? ORDER BY next_attempt_at
`

type DueOutboxParams struct {
	Connection    string
	NextAttemptAt int64
}

func (q *Queries) DueOutbox(ctx context.Context, arg DueOutboxParams) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, dueOutbox, arg.Connection, arg.NextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.Connection,
			&i.RunID,
			&i.Body,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endRunWait = `-- name: EndRunWait :exec
UPDATE runs SET waited_ms = waited_ms + MAX(?1 - COALESCE(waiting_since, ?1), 0),
  waiting_since = NULL, resumes_at = NULL, updated_at = ?1
WHERE connection = ?2 AND id = ?3
`

type EndRunWaitParams struct {
	Now        int64
	Connection string
	ID         string
}

// End the current wait, folding it into the total. Called by whoever takes
// the run out of waiting, before it runs again or times out, so the wait in
// progress is counted exactly once whichever of the two happens.
func (q *Queries) EndRunWait(ctx context.Context, arg EndRunWaitParams) error {
	_, err := q.db.ExecContext(ctx, endRunWait, arg.Now, arg.Connection, arg.ID)
	return err
}

const freeSlots = `-- name: FreeSlots :exec
DELETE FROM slots WHERE connection = ? AND session_id = ?
`

type FreeSlotsParams struct {
	Connection string
	SessionID  string
}

func (q *Queries) FreeSlots(ctx context.Context, arg FreeSlotsParams) error {
	_, err := q.db.ExecContext(ctx, freeSlots, arg.Connection, arg.SessionID)
	return err
}

const getRun = `-- name: GetRun :one
SELECT connection, id, session_id, harness, model, state, spec, account, resumes_at, reason, created_at, updated_at, started_at, waited_ms, waiting_since, account_switches, had_grants, spent FROM runs WHERE connection = ? AND id = ?
`

type GetRunParams struct {
	Connection string
	ID         string
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, arg.Connection, arg.ID)
	var i Run
	err := row.Scan(
		&i.Connection,
		&i.ID,
		&i.SessionID,
		&i.Harness,
		&i.Model,
		&i.State,
		&i.Spec,
		&i.Account,
		&i.ResumesAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.WaitedMs,
		&i.WaitingSince,
		&i.AccountSwitches,
		&i.HadGrants,
		&i.Spent,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT connection, id, harness, native_id, account, workdir, state, created_at, last_used_at, sources, close_reason, close_requested_at, closed_at, reclaimed_at, reported_at FROM sessions WHERE connection = ? AND id = ?
`

type GetSessionParams struct {
	Connection string
	ID         string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.Connection, arg.ID)
	var i Session
	err := row.Scan(
		&i.Connection,
		&i.ID,
		&i.Harness,
		&i.NativeID,
		&i.Account,
		&i.Workdir,
		&i.State,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Sources,
		&i.CloseReason,
		&i.CloseRequestedAt,
		&i.ClosedAt,
		&i.ReclaimedAt,
		&i.ReportedAt,
	)
	return i, err
}

const hasUnackedEvents = `-- name: HasUnackedEvents :one
SELECT EXISTS (SELECT 1 FROM events WHERE connection = ? AND run_id = ? AND acked = 0)
`

type HasUnackedEventsParams struct {
	Connection string
	RunID      string
}

func (q *Queries) HasUnackedEvents(ctx context.Context, arg HasUnackedEventsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUnackedEvents, arg.Connection, arg.RunID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const heldRunInSession = `-- name: HeldRunInSession :one
SELECT CAST(COALESCE((SELECT r.id FROM runs r WHERE r.connection = ?1 AND r.session_id = ?2
  AND r.state IN ('claimed', 'preparing', 'running', 'waiting')), '') AS TEXT)
`

type HeldRunInSessionParams struct {
	Connection string
	ID         string
}

func (q *Queries) HeldRunInSession(ctx context.Context, arg HeldRunInSessionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, heldRunInSession, arg.Connection, arg.ID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const idleSessions = `-- name: IdleSessions :many
SELECT connection, id, harness, native_id, account, workdir, state, created_at, last_used_at, sources, close_reason, close_requested_at, closed_at, reclaimed_at, reported_at FROM sessions s WHERE s.state = 'open' AND s.last_used_at > 0 AND s.last_used_at < ?1
  AND (?2 = 0 OR s.workdir != '')
  AND NOT EXISTS (SELECT 1 FROM runs r WHERE r.connection = s.connection AND r.session_id = s.id
    AND r.state IN ('claimed', 'preparing', 'running', 'waiting'))
ORDER BY s.last_used_at, s.connection, s.id
LIMIT ?3
`

type IdleSessionsParams struct {
	IdleSince   int64
	WithWorkdir interface{}
	Max         int64
}

// Open sessions nothing has run in since before idle_since, longest idle
// first: the idle TTL's and disk pressure's candidates. Disk pressure asks
// only for sessions with a workdir, since the rest free nothing and would
// fill its page.
func (q *Queries) IdleSessions(ctx context.Context, arg IdleSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, idleSessions, arg.IdleSince, arg.WithWorkdir, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.Harness,
			&i.NativeID,
			&i.Account,
			&i.Workdir,
			&i.State,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Sources,
			&i.CloseReason,
			&i.CloseRequestedAt,
			&i.ClosedAt,
			&i.ReclaimedAt,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastEvent = `-- name: LastEvent :one
SELECT seq, body FROM events WHERE connection = ? AND run_id = ? ORDER BY seq DESC LIMIT 1
`

type LastEventParams struct {
	Connection string
	RunID      string
}

type LastEventRow struct {
	Seq  int64
	Body string
}

// The last event a run spooled, whole. The body carries the moment the event
// was written, which is the latest time anything is known to have been true
// of a run whose process is gone: runs.updated_at moves only when a column
// does, so for a turn that streamed for three hours it still says when the
// run reached running. No rows for a run that never spoke.
func (q *Queries) LastEvent(ctx context.Context, arg LastEventParams) (LastEventRow, error) {
	row := q.db.QueryRowContext(ctx, lastEvent, arg.Connection, arg.RunID)
	var i LastEventRow
	err := row.Scan(&i.Seq, &i.Body)
	return i, err
}

const lastEventSeq = `-- name: LastEventSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER) FROM events WHERE connection = ? AND run_id = ?
`

type LastEventSeqParams struct {
	Connection string
	RunID      string
}

// The last event a run spooled, acknowledged or not: a result's last_seq.
func (q *Queries) LastEventSeq(ctx context.Context, arg LastEventSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastEventSeq, arg.Connection, arg.RunID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT harness, label, limited_until, state, updated_at FROM accounts WHERE harness = ? ORDER BY label
`

func (q *Queries) ListAccounts(ctx context.Context, harness string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, harness)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.Harness,
			&i.Label,
			&i.LimitedUntil,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccountWindows = `-- name: ListAllAccountWindows :many
SELECT harness, label, name, used_percent, resets_at, updated_at FROM account_windows ORDER BY harness, label, name
`

// Every window this runner has heard of, across accounts: what the health
// report and `yad account list` read, grouped by account in Go.
func (q *Queries) ListAllAccountWindows(ctx context.Context) ([]AccountWindow, error) {
	rows, err := q.db.QueryContext(ctx, listAllAccountWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountWindow{}
	for rows.Next() {
		var i AccountWindow
		if err := rows.Scan(
			&i.Harness,
			&i.Label,
			&i.Name,
			&i.UsedPercent,
			&i.ResetsAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccounts = `-- name: ListAllAccounts :many
SELECT harness, label, limited_until, state, updated_at FROM accounts ORDER BY harness, label
`

// Every account this runner has a row for, across harnesses: what
// `yad account list` and the health report read. The owner's order lives in
// config.toml, so this sorts only for a stable read.
func (q *Queries) ListAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.Harness,
			&i.Label,
			&i.LimitedUntil,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllHeldRuns = `-- name: ListAllHeldRuns :many
SELECT connection, id, session_id, harness, model, state, spec, account, resumes_at, reason, created_at, updated_at, started_at, waited_ms, waiting_since, account_switches, had_grants, spent FROM runs
WHERE state IN ('claimed', 'preparing', 'running', 'waiting')
ORDER BY created_at
`

// What `yad status` lists: every run held, across connections.
func (q *Queries) ListAllHeldRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listAllHeldRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.State,
			&i.Spec,
			&i.Account,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.WaitedMs,
			&i.WaitingSince,
			&i.AccountSwitches,
			&i.HadGrants,
			&i.Spent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeldRuns = `-- name: ListHeldRuns :many
SELECT connection, id, session_id, harness, model, state, spec, account, resumes_at, reason, created_at, updated_at, started_at, waited_ms, waiting_since, account_switches, had_grants, spent FROM runs
WHERE connection = ? AND state IN ('claimed', 'preparing', 'running', 'waiting')
ORDER BY created_at
`

func (q *Queries) ListHeldRuns(ctx context.Context, connection string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listHeldRuns, connection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.State,
			&i.Spec,
			&i.Account,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.WaitedMs,
			&i.WaitingSince,
			&i.AccountSwitches,
			&i.HadGrants,
			&i.Spent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportingRuns = `-- name: ListReportingRuns :many
SELECT r.connection, r.id, r.session_id, r.harness, r.model, r.state, r.spec, r.account, r.resumes_at, r.reason, r.created_at, r.updated_at, r.started_at, r.waited_ms, r.waiting_since, r.account_switches, r.had_grants, r.spent FROM runs r JOIN outbox o ON o.connection = r.connection AND o.run_id = r.id
WHERE r.connection = ? ORDER BY r.created_at
`

// A finished run whose result the hub has not acknowledged is still this
// runner's: listing it keeps its lease alive, so a hub outage longer than a
// lease does not turn a finished run into a lost one.
func (q *Queries) ListReportingRuns(ctx context.Context, connection string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listReportingRuns, connection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.State,
			&i.Spec,
			&i.Account,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.WaitedMs,
			&i.WaitingSince,
			&i.AccountSwitches,
			&i.HadGrants,
			&i.Spent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.connection, s.id, s.harness, s.native_id, s.workdir, s.state, s.created_at, s.last_used_at,
  s.close_reason, s.close_requested_at, s.closed_at, s.reclaimed_at, s.reported_at,
  CAST(COALESCE((SELECT r.id FROM runs r
    WHERE r.connection = s.connection AND r.session_id = s.id
      AND r.state IN ('claimed', 'preparing', 'running', 'waiting')), '') AS TEXT) AS live_run,
  CAST((SELECT count(*) FROM runs r WHERE r.connection = s.connection AND r.session_id = s.id) AS INTEGER) AS runs
FROM sessions s
ORDER BY s.last_used_at DESC, s.connection, s.id
`

type ListSessionsRow struct {
	Connection       string
	ID               string
	Harness          string
	NativeID         sql.NullString
	Workdir          string
	State            string
	CreatedAt        int64
	LastUsedAt       int64
	CloseReason      sql.NullString
	CloseRequestedAt sql.NullInt64
	ClosedAt         sql.NullInt64
	ReclaimedAt      sql.NullInt64
	ReportedAt       sql.NullInt64
	LiveRun          string
	Runs             int64
}

// What `yad sessions` lists: every session, most recently used first, with
// the run live in it, if any.
func (q *Queries) ListSessions(ctx context.Context) ([]ListSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.Harness,
			&i.NativeID,
			&i.Workdir,
			&i.State,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.CloseReason,
			&i.CloseRequestedAt,
			&i.ClosedAt,
			&i.ReclaimedAt,
			&i.ReportedAt,
			&i.LiveRun,
			&i.Runs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingRuns = `-- name: ListWaitingRuns :many
SELECT connection, id, session_id, harness, model, state, spec, account, resumes_at, reason, created_at, updated_at, started_at, waited_ms, waiting_since, account_switches, had_grants, spent FROM runs WHERE state = 'waiting' ORDER BY created_at, connection, id
`

// Every parked run, across connections, for the collector: it ends the ones
// whose cap has run out on a connection no sync loop is serving, and it never
// starts one. A loop resuming its own connection's parked runs reads them from
// the listing it already makes. Ordered oldest first so the run that has waited
// longest is dealt with first.
func (q *Queries) ListWaitingRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listWaitingRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.SessionID,
			&i.Harness,
			&i.Model,
			&i.State,
			&i.Spec,
			&i.Account,
			&i.ResumesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.WaitedMs,
			&i.WaitingSince,
			&i.AccountSwitches,
			&i.HadGrants,
			&i.Spent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxDepth = `-- name: OutboxDepth :one
SELECT count(*) FROM outbox
`

func (q *Queries) OutboxDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, outboxDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const putOutbox = `-- name: PutOutbox :exec
INSERT INTO outbox (connection, run_id, body, next_attempt_at) VALUES (?, ?, ?, ?)
ON CONFLICT (connection, run_id) DO NOTHING
`

type PutOutboxParams struct {
	Connection    string
	RunID         string
	Body          string
	NextAttemptAt int64
}

func (q *Queries) PutOutbox(ctx context.Context, arg PutOutboxParams) error {
	_, err := q.db.ExecContext(ctx, putOutbox,
		arg.Connection,
		arg.RunID,
		arg.Body,
		arg.NextAttemptAt,
	)
	return err
}

const requestSessionClose = `-- name: RequestSessionClose :exec
UPDATE sessions SET close_requested_at = COALESCE(close_requested_at, ?1),
  close_reason = COALESCE(close_reason, ?2)
WHERE connection = ?3 AND id = ?4 AND state = 'open'
`

type RequestSessionCloseParams struct {
	Now        sql.NullInt64
	Reason     sql.NullString
	Connection string
	ID         string
}

// The first reason asked for stands: a hub's close repeated on every sync
// must not turn the owner's into the hub's.
func (q *Queries) RequestSessionClose(ctx context.Context, arg RequestSessionCloseParams) error {
	_, err := q.db.ExecContext(ctx, requestSessionClose,
		arg.Now,
		arg.Reason,
		arg.Connection,
		arg.ID,
	)
	return err
}

const retryOutbox = `-- name: RetryOutbox :exec
UPDATE outbox SET attempts = attempts + 1, next_attempt_at = ?, last_error = ? WHERE connection = ? AND run_id = ?
`

type RetryOutboxParams struct {
	NextAttemptAt int64
	LastError     sql.NullString
	Connection    string
	RunID         string
}

func (q *Queries) RetryOutbox(ctx context.Context, arg RetryOutboxParams) error {
	_, err := q.db.ExecContext(ctx, retryOutbox,
		arg.NextAttemptAt,
		arg.LastError,
		arg.Connection,
		arg.RunID,
	)
	return err
}

const runsWithUnackedEvents = `-- name: RunsWithUnackedEvents :many
SELECT DISTINCT run_id FROM events WHERE connection = ? AND acked = 0 ORDER BY run_id
`

func (q *Queries) RunsWithUnackedEvents(ctx context.Context, connection string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, runsWithUnackedEvents, connection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var run_id string
		if err := rows.Scan(&run_id); err != nil {
			return nil, err
		}
		items = append(items, run_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionSlot = `-- name: SessionSlot :one
SELECT slot FROM slots WHERE repo = ? AND connection = ? AND session_id = ?
`

type SessionSlotParams struct {
	Repo       string
	Connection string
	SessionID  string
}

func (q *Queries) SessionSlot(ctx context.Context, arg SessionSlotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sessionSlot, arg.Repo, arg.Connection, arg.SessionID)
	var slot int64
	err := row.Scan(&slot)
	return slot, err
}

const sessionsCloseRequested = `-- name: SessionsCloseRequested :many
SELECT connection, id, harness, native_id, account, workdir, state, created_at, last_used_at, sources, close_reason, close_requested_at, closed_at, reclaimed_at, reported_at FROM sessions s WHERE s.state = 'open' AND s.close_requested_at IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM runs r WHERE r.connection = s.connection AND r.session_id = s.id
    AND r.state IN ('claimed', 'preparing', 'running', 'waiting'))
ORDER BY s.close_requested_at
`

func (q *Queries) SessionsCloseRequested(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, sessionsCloseRequested)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.Harness,
			&i.NativeID,
			&i.Account,
			&i.Workdir,
			&i.State,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Sources,
			&i.CloseReason,
			&i.CloseRequestedAt,
			&i.ClosedAt,
			&i.ReclaimedAt,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountLimit = `-- name: SetAccountLimit :exec
INSERT INTO accounts (harness, label, state, limited_until, updated_at) VALUES (?, ?, 'limited', ?, ?)
ON CONFLICT (harness, label) DO UPDATE SET state = excluded.state, limited_until = excluded.limited_until, updated_at = excluded.updated_at
`

type SetAccountLimitParams struct {
	Harness      string
	Label        string
	LimitedUntil sql.NullInt64
	UpdatedAt    int64
}

// A usage limit: the account is at one until its window resets. The state and
// the reset are written together because they are one fact: a limited account
// with no reset is a park nothing ends, and a reset with no state is a limit
// nobody acts on.
func (q *Queries) SetAccountLimit(ctx context.Context, arg SetAccountLimitParams) error {
	_, err := q.db.ExecContext(ctx, setAccountLimit,
		arg.Harness,
		arg.Label,
		arg.LimitedUntil,
		arg.UpdatedAt,
	)
	return err
}

const setAccountState = `-- name: SetAccountState :exec
INSERT INTO accounts (harness, label, state, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT (harness, label) DO UPDATE SET state = excluded.state, updated_at = excluded.updated_at
`

type SetAccountStateParams struct {
	Harness   string
	Label     string
	State     string
	UpdatedAt int64
}

// The state an account is in, without disturbing limited_until: DEV-27 owns
// the limit, this owns free and needs_login.
func (q *Queries) SetAccountState(ctx context.Context, arg SetAccountStateParams) error {
	_, err := q.db.ExecContext(ctx, setAccountState,
		arg.Harness,
		arg.Label,
		arg.State,
		arg.UpdatedAt,
	)
	return err
}

const setAccountWindow = `-- name: SetAccountWindow :exec
INSERT INTO account_windows (harness, label, name, used_percent, resets_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (harness, label, name) DO UPDATE SET used_percent = excluded.used_percent, resets_at = excluded.resets_at, updated_at = excluded.updated_at
WHERE excluded.updated_at >= account_windows.updated_at
`

type SetAccountWindowParams struct {
	Harness     string
	Label       string
	Name        string
	UsedPercent float64
	ResetsAt    sql.NullInt64
	UpdatedAt   int64
}

// One window's latest use and reset. An upsert per window rather than a
// rewrite of a whole snapshot, so two turns finishing on the same account at
// once cannot lose each other's windows: capacity is a shared pool and nothing
// reserves an account.
//
// The row keeps the most recently *recorded* snapshot, not the most recently
// observed one. updated_at is when the turn ended, which is the only time any
// caller has: a window carries its use and its reset and never the moment the
// harness said them. So this resolves two turns racing to write - the one that
// started earlier and arrived later no longer wins - and does not resolve two
// turns that observed at different moments, since a long turn can observe
// early and still end last.
//
// One consequence worth knowing before changing it: the comparison is against
// a wall clock, and :exec discards the row count. A clock stepped backwards
// silently skips every window write for an account written just before the
// step, until the clock passes the stored stamp. That is confined to what a
// hub is shown - SetAccountLimit carries no such WHERE, so parking an account
// still works, and RefillAt ignores a reset that has already passed.
func (q *Queries) SetAccountWindow(ctx context.Context, arg SetAccountWindowParams) error {
	_, err := q.db.ExecContext(ctx, setAccountWindow,
		arg.Harness,
		arg.Label,
		arg.Name,
		arg.UsedPercent,
		arg.ResetsAt,
		arg.UpdatedAt,
	)
	return err
}

const setRunAccount = `-- name: SetRunAccount :exec
UPDATE runs SET account = ?, updated_at = ? WHERE connection = ? AND id = ?
`

type SetRunAccountParams struct {
	Account    sql.NullString
	UpdatedAt  int64
	Connection string
	ID         string
}

func (q *Queries) SetRunAccount(ctx context.Context, arg SetRunAccountParams) error {
	_, err := q.db.ExecContext(ctx, setRunAccount,
		arg.Account,
		arg.UpdatedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const setRunStarted = `-- name: SetRunStarted :exec
UPDATE runs SET started_at = ?, updated_at = ? WHERE connection = ? AND id = ? AND started_at IS NULL
`

type SetRunStartedParams struct {
	StartedAt  sql.NullInt64
	UpdatedAt  int64
	Connection string
	ID         string
}

// The moment the run first reached preparing, kept so a run that waited
// between two turns still reports the whole of its duration. Written once:
// a resumed run is the same run, not a new one.
func (q *Queries) SetRunStarted(ctx context.Context, arg SetRunStartedParams) error {
	_, err := q.db.ExecContext(ctx, setRunStarted,
		arg.StartedAt,
		arg.UpdatedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const setRunState = `-- name: SetRunState :exec
UPDATE runs SET state = ?, resumes_at = ?, reason = ?, updated_at = ? WHERE connection = ? AND id = ?
`

type SetRunStateParams struct {
	State      string
	ResumesAt  sql.NullInt64
	Reason     sql.NullString
	UpdatedAt  int64
	Connection string
	ID         string
}

func (q *Queries) SetRunState(ctx context.Context, arg SetRunStateParams) error {
	_, err := q.db.ExecContext(ctx, setRunState,
		arg.State,
		arg.ResumesAt,
		arg.Reason,
		arg.UpdatedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const setRunWaiting = `-- name: SetRunWaiting :exec
UPDATE runs SET state = 'waiting', resumes_at = ?, waiting_since = ?, account_switches = ?,
  spent = ?, reason = ?, updated_at = ? WHERE connection = ? AND id = ?
`

type SetRunWaitingParams struct {
	ResumesAt       sql.NullInt64
	WaitingSince    sql.NullInt64
	AccountSwitches int64
	Spent           sql.NullString
	Reason          sql.NullString
	UpdatedAt       int64
	Connection      string
	ID              string
}

// Park the run on a usage limit. The state, the moment it comes back, when
// the wait began and what the run has cost so far, in one statement: a park
// missing any of them is a run no sync can finish or a metric that
// silently resets.
func (q *Queries) SetRunWaiting(ctx context.Context, arg SetRunWaitingParams) error {
	_, err := q.db.ExecContext(ctx, setRunWaiting,
		arg.ResumesAt,
		arg.WaitingSince,
		arg.AccountSwitches,
		arg.Spent,
		arg.Reason,
		arg.UpdatedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const setSessionNativeID = `-- name: SetSessionNativeID :exec
UPDATE sessions SET native_id = ?, last_used_at = ? WHERE connection = ? AND id = ?
`

type SetSessionNativeIDParams struct {
	NativeID   sql.NullString
	LastUsedAt int64
	Connection string
	ID         string
}

func (q *Queries) SetSessionNativeID(ctx context.Context, arg SetSessionNativeIDParams) error {
	_, err := q.db.ExecContext(ctx, setSessionNativeID,
		arg.NativeID,
		arg.LastUsedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const setSessionReclaimed = `-- name: SetSessionReclaimed :exec
UPDATE sessions SET reclaimed_at = ? WHERE connection = ? AND id = ?
`

type SetSessionReclaimedParams struct {
	ReclaimedAt sql.NullInt64
	Connection  string
	ID          string
}

func (q *Queries) SetSessionReclaimed(ctx context.Context, arg SetSessionReclaimedParams) error {
	_, err := q.db.ExecContext(ctx, setSessionReclaimed, arg.ReclaimedAt, arg.Connection, arg.ID)
	return err
}

const setSessionReported = `-- name: SetSessionReported :exec
UPDATE sessions SET reported_at = ? WHERE connection = ? AND id = ? AND reported_at IS NULL
`

type SetSessionReportedParams struct {
	ReportedAt sql.NullInt64
	Connection string
	ID         string
}

func (q *Queries) SetSessionReported(ctx context.Context, arg SetSessionReportedParams) error {
	_, err := q.db.ExecContext(ctx, setSessionReported, arg.ReportedAt, arg.Connection, arg.ID)
	return err
}

const setSessionSources = `-- name: SetSessionSources :exec
UPDATE sessions SET sources = ? WHERE connection = ? AND id = ?
`

type SetSessionSourcesParams struct {
	Sources    sql.NullString
	Connection string
	ID         string
}

func (q *Queries) SetSessionSources(ctx context.Context, arg SetSessionSourcesParams) error {
	_, err := q.db.ExecContext(ctx, setSessionSources, arg.Sources, arg.Connection, arg.ID)
	return err
}

const setSessionState = `-- name: SetSessionState :exec
UPDATE sessions SET state = ?, last_used_at = ? WHERE connection = ? AND id = ?
`

type SetSessionStateParams struct {
	State      string
	LastUsedAt int64
	Connection string
	ID         string
}

func (q *Queries) SetSessionState(ctx context.Context, arg SetSessionStateParams) error {
	_, err := q.db.ExecContext(ctx, setSessionState,
		arg.State,
		arg.LastUsedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const setSessionWorkdir = `-- name: SetSessionWorkdir :exec
UPDATE sessions SET workdir = ?, last_used_at = ? WHERE connection = ? AND id = ?
`

type SetSessionWorkdirParams struct {
	Workdir    string
	LastUsedAt int64
	Connection string
	ID         string
}

func (q *Queries) SetSessionWorkdir(ctx context.Context, arg SetSessionWorkdirParams) error {
	_, err := q.db.ExecContext(ctx, setSessionWorkdir,
		arg.Workdir,
		arg.LastUsedAt,
		arg.Connection,
		arg.ID,
	)
	return err
}

const slotsInUse = `-- name: SlotsInUse :many
SELECT slot FROM slots WHERE repo = ? ORDER BY slot
`

func (q *Queries) SlotsInUse(ctx context.Context, repo string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, slotsInUse, repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var slot int64
		if err := rows.Scan(&slot); err != nil {
			return nil, err
		}
		items = append(items, slot)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spoolDepth = `-- name: SpoolDepth :one
SELECT count(*) FROM events WHERE acked = 0
`

func (q *Queries) SpoolDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, spoolDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const stampUnknownLastUsed = `-- name: StampUnknownLastUsed :execrows
UPDATE sessions SET last_used_at = ?1 WHERE state = 'open' AND last_used_at <= 0
`

// A last-used stamp that is missing is unknown, never ancient: the idle TTL
// starts from when collection first saw the session. Multica's collector
// read a missing stamp as the epoch and reclaimed everything at once.
func (q *Queries) StampUnknownLastUsed(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, stampUnknownLastUsed, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const takeSlot = `-- name: TakeSlot :exec
INSERT INTO slots (repo, slot, connection, session_id) VALUES (?, ?, ?, ?)
`

type TakeSlotParams struct {
	Repo       string
	Slot       int64
	Connection string
	SessionID  string
}

func (q *Queries) TakeSlot(ctx context.Context, arg TakeSlotParams) error {
	_, err := q.db.ExecContext(ctx, takeSlot,
		arg.Repo,
		arg.Slot,
		arg.Connection,
		arg.SessionID,
	)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = ? WHERE connection = ? AND id = ?
`

type TouchSessionParams struct {
	LastUsedAt int64
	Connection string
	ID         string
}

// A session's idle time runs from the end of its last run, not its start: a
// run of three hours leaves a session used three hours later than it began.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastUsedAt, arg.Connection, arg.ID)
	return err
}

const unackedEvents = `-- name: UnackedEvents :many
SELECT seq, body FROM events WHERE connection = ? AND run_id = ? AND acked = 0 ORDER BY seq LIMIT ?
`

type UnackedEventsParams struct {
	Connection string
	RunID      string
	Limit      int64
}

type UnackedEventsRow struct {
	Seq  int64
	Body string
}

func (q *Queries) UnackedEvents(ctx context.Context, arg UnackedEventsParams) ([]UnackedEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, unackedEvents, arg.Connection, arg.RunID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnackedEventsRow{}
	for rows.Next() {
		var i UnackedEventsRow
		if err := rows.Scan(&i.Seq, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unreclaimedSessions = `-- name: UnreclaimedSessions :many
SELECT connection, id, harness, native_id, account, workdir, state, created_at, last_used_at, sources, close_reason, close_requested_at, closed_at, reclaimed_at, reported_at FROM sessions WHERE state != 'open' AND reclaimed_at IS NULL ORDER BY closed_at
`

func (q *Queries) UnreclaimedSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, unreclaimedSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.Harness,
			&i.NativeID,
			&i.Account,
			&i.Workdir,
			&i.State,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Sources,
			&i.CloseReason,
			&i.CloseRequestedAt,
			&i.ClosedAt,
			&i.ReclaimedAt,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unreportedClosedSessions = `-- name: UnreportedClosedSessions :many
SELECT connection, id, harness, native_id, account, workdir, state, created_at, last_used_at, sources, close_reason, close_requested_at, closed_at, reclaimed_at, reported_at FROM sessions WHERE connection = ?1 AND state != 'open' AND reported_at IS NULL
ORDER BY closed_at, id LIMIT ?2
`

type UnreportedClosedSessionsParams struct {
	Connection string
	Max        int64
}

func (q *Queries) UnreportedClosedSessions(ctx context.Context, arg UnreportedClosedSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, unreportedClosedSessions, arg.Connection, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.Connection,
			&i.ID,
			&i.Harness,
			&i.NativeID,
			&i.Account,
			&i.Workdir,
			&i.State,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Sources,
			&i.CloseReason,
			&i.CloseRequestedAt,
			&i.ClosedAt,
			&i.ReclaimedAt,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
