// Command openapigen writes protocol/v1/openapi.yaml from yad hub's operations.
// Run it through `make generate`; the hub's drift test fails when the committed
// file and the code disagree.
package main

import (
	"fmt"
	"os"

	"github.com/skkap/yad/internal/hub"
)

func main() {
	out := "protocol/v1/openapi.yaml"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}
	b, err := hub.New(hub.Options{}).OpenAPI()
	if err != nil {
		fmt.Fprintln(os.Stderr, "openapigen:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(out, append(header, b...), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "openapigen:", err)
		os.Exit(1)
	}
}

var header = []byte("# Code generated by internal/hub/cmd/openapigen from protocol/v1. DO NOT EDIT.\n# Regenerate with `make generate`.\n")
