// Command openapigen writes the two generated OpenAPI documents from yad hub's
// operations: the runner protocol's and the service API's. Run it through
// `make generate`; the hub's drift tests fail when a committed file and the
// code disagree.
package main

import (
	"fmt"
	"os"

	"github.com/skkap/yad/internal/hub"
)

func main() {
	protocolOut, serviceOut := "protocol/v1/openapi.yaml", "protocol/hubapi/openapi.yaml"
	if len(os.Args) > 2 {
		protocolOut, serviceOut = os.Args[1], os.Args[2]
	}
	h := hub.New(hub.Options{})
	for _, doc := range []struct {
		out string
		gen func() ([]byte, error)
		src string
	}{
		{protocolOut, h.OpenAPI, "protocol/v1"},
		{serviceOut, h.ServiceOpenAPI, "protocol/hubapi"},
	} {
		b, err := doc.gen()
		if err != nil {
			fmt.Fprintln(os.Stderr, "openapigen:", err)
			os.Exit(1)
		}
		header := []byte("# Code generated by internal/hub/cmd/openapigen from " + doc.src + ". DO NOT EDIT.\n# Regenerate with `make generate`.\n")
		if err := os.WriteFile(doc.out, append(header, b...), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "openapigen:", err)
			os.Exit(1)
		}
	}
}
